// Package meta provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package meta

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// AggregateStatsResponse defines model for AggregateStatsResponse.
type AggregateStatsResponse struct {
	TotalCids         int `json:"total_cids"`
	TotalPinners      int `json:"total_pinners"`
	TotalStorageBytes int `json:"total_storage_bytes"`
}

// CIDExportResponse defines model for CIDExportResponse.
type CIDExportResponse struct {
	Bucket       string                 `json:"bucket"`
	Cid          string                 `json:"cid"`
	CreatedAt    string                 `json:"created_at"`
	ObjectKey    string                 `json:"object_key"`
	SharedObject map[string]interface{} `json:"shared_object"`
	SiaObjectId  string                 `json:"sia_object_id"`
	SizeBytes    int                    `json:"size_bytes"`
	UpdatedAt    string                 `json:"updated_at"`
}

// CIDStatsResponse defines model for CIDStatsResponse.
type CIDStatsResponse struct {
	Cid                 string  `json:"cid"`
	FirstPinnedAt       *string `json:"first_pinned_at,omitempty"`
	IsUnlimited         *bool   `json:"is_unlimited,omitempty"`
	LastPinnedAt        *string `json:"last_pinned_at,omitempty"`
	Pinned              bool    `json:"pinned"`
	PinnerCount         int     `json:"pinner_count"`
	QuotaRunsOutAt      *string `json:"quota_runs_out_at,omitempty"`
	SizeBytes           int     `json:"size_bytes"`
	StorageDays         float32 `json:"storage_days"`
	TotalQuotaBytes     *int    `json:"total_quota_bytes,omitempty"`
	TotalRemainingBytes *int    `json:"total_remaining_bytes,omitempty"`
	TotalUsedBytes      *int    `json:"total_used_bytes,omitempty"`
}

// DAGBlock defines model for DAGBlock.
type DAGBlock struct {
	Cid       string             `json:"cid"`
	Links     []DAGLink          `json:"links"`
	SiaObject *CIDExportResponse `json:"sia_object,omitempty"`
	Size      int                `json:"size"`
}

// DAGExportResponse defines model for DAGExportResponse.
type DAGExportResponse struct {
	Blocks         []DAGBlock `json:"blocks"`
	RootCid        string     `json:"root_cid"`
	TotalBlocks    int        `json:"total_blocks"`
	TotalSizeBytes int        `json:"total_size_bytes"`
}

// DAGLink defines model for DAGLink.
type DAGLink struct {
	Cid   string `json:"cid"`
	Index int    `json:"index"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Details *string `json:"details,omitempty"`
	Reason  string  `json:"reason"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorDetail `json:"error"`
}

// ProtocolStat defines model for ProtocolStat.
type ProtocolStat struct {
	Protocol          string `json:"protocol"`
	TotalPins         int    `json:"total_pins"`
	TotalStorageBytes int    `json:"total_storage_bytes"`
	TotalUploads      int    `json:"total_uploads"`
}

// ProtocolStatsResponse defines model for ProtocolStatsResponse.
type ProtocolStatsResponse struct {
	Protocols []ProtocolStat `json:"protocols"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApiExportCidCidDag request
	GetApiExportCidCidDag(ctx context.Context, cid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiExportCidCidSiaObject request
	GetApiExportCidCidSiaObject(ctx context.Context, cid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiStatsAggregate request
	GetApiStatsAggregate(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiStatsCidCid request
	GetApiStatsCidCid(ctx context.Context, cid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiStatsProtocols request
	GetApiStatsProtocols(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApiExportCidCidDag(ctx context.Context, cid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiExportCidCidDagRequest(c.Server, cid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiExportCidCidSiaObject(ctx context.Context, cid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiExportCidCidSiaObjectRequest(c.Server, cid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiStatsAggregate(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiStatsAggregateRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiStatsCidCid(ctx context.Context, cid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiStatsCidCidRequest(c.Server, cid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiStatsProtocols(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiStatsProtocolsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiExportCidCidDagRequest generates requests for GetApiExportCidCidDag
func NewGetApiExportCidCidDagRequest(server string, cid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "cid", cid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/export/cid/%s/dag", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiExportCidCidSiaObjectRequest generates requests for GetApiExportCidCidSiaObject
func NewGetApiExportCidCidSiaObjectRequest(server string, cid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "cid", cid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/export/cid/%s/sia-object", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiStatsAggregateRequest generates requests for GetApiStatsAggregate
func NewGetApiStatsAggregateRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/stats/aggregate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiStatsCidCidRequest generates requests for GetApiStatsCidCid
func NewGetApiStatsCidCidRequest(server string, cid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "cid", cid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/stats/cid/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiStatsProtocolsRequest generates requests for GetApiStatsProtocols
func NewGetApiStatsProtocolsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/stats/protocols")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetApiExportCidCidDagWithResponse request
	GetApiExportCidCidDagWithResponse(ctx context.Context, cid string, reqEditors ...RequestEditorFn) (*GetApiExportCidCidDagResponse, error)

	// GetApiExportCidCidSiaObjectWithResponse request
	GetApiExportCidCidSiaObjectWithResponse(ctx context.Context, cid string, reqEditors ...RequestEditorFn) (*GetApiExportCidCidSiaObjectResponse, error)

	// GetApiStatsAggregateWithResponse request
	GetApiStatsAggregateWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiStatsAggregateResponse, error)

	// GetApiStatsCidCidWithResponse request
	GetApiStatsCidCidWithResponse(ctx context.Context, cid string, reqEditors ...RequestEditorFn) (*GetApiStatsCidCidResponse, error)

	// GetApiStatsProtocolsWithResponse request
	GetApiStatsProtocolsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiStatsProtocolsResponse, error)
}

type GetApiExportCidCidDagResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DAGExportResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiExportCidCidDagResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiExportCidCidDagResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiExportCidCidDagResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiExportCidCidSiaObjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CIDExportResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiExportCidCidSiaObjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiExportCidCidSiaObjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiExportCidCidSiaObjectResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiStatsAggregateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AggregateStatsResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiStatsAggregateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiStatsAggregateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiStatsAggregateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiStatsCidCidResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CIDStatsResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiStatsCidCidResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiStatsCidCidResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiStatsCidCidResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiStatsProtocolsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProtocolStatsResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiStatsProtocolsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiStatsProtocolsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiStatsProtocolsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetApiExportCidCidDagWithResponse request returning *GetApiExportCidCidDagResponse
func (c *ClientWithResponses) GetApiExportCidCidDagWithResponse(ctx context.Context, cid string, reqEditors ...RequestEditorFn) (*GetApiExportCidCidDagResponse, error) {
	rsp, err := c.GetApiExportCidCidDag(ctx, cid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiExportCidCidDagResponse(rsp)
}

// GetApiExportCidCidSiaObjectWithResponse request returning *GetApiExportCidCidSiaObjectResponse
func (c *ClientWithResponses) GetApiExportCidCidSiaObjectWithResponse(ctx context.Context, cid string, reqEditors ...RequestEditorFn) (*GetApiExportCidCidSiaObjectResponse, error) {
	rsp, err := c.GetApiExportCidCidSiaObject(ctx, cid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiExportCidCidSiaObjectResponse(rsp)
}

// GetApiStatsAggregateWithResponse request returning *GetApiStatsAggregateResponse
func (c *ClientWithResponses) GetApiStatsAggregateWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiStatsAggregateResponse, error) {
	rsp, err := c.GetApiStatsAggregate(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiStatsAggregateResponse(rsp)
}

// GetApiStatsCidCidWithResponse request returning *GetApiStatsCidCidResponse
func (c *ClientWithResponses) GetApiStatsCidCidWithResponse(ctx context.Context, cid string, reqEditors ...RequestEditorFn) (*GetApiStatsCidCidResponse, error) {
	rsp, err := c.GetApiStatsCidCid(ctx, cid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiStatsCidCidResponse(rsp)
}

// GetApiStatsProtocolsWithResponse request returning *GetApiStatsProtocolsResponse
func (c *ClientWithResponses) GetApiStatsProtocolsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiStatsProtocolsResponse, error) {
	rsp, err := c.GetApiStatsProtocols(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiStatsProtocolsResponse(rsp)
}

// ParseGetApiExportCidCidDagResponse parses an HTTP response from a GetApiExportCidCidDagWithResponse call
func ParseGetApiExportCidCidDagResponse(rsp *http.Response) (*GetApiExportCidCidDagResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiExportCidCidDagResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DAGExportResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiExportCidCidSiaObjectResponse parses an HTTP response from a GetApiExportCidCidSiaObjectWithResponse call
func ParseGetApiExportCidCidSiaObjectResponse(rsp *http.Response) (*GetApiExportCidCidSiaObjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiExportCidCidSiaObjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CIDExportResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiStatsAggregateResponse parses an HTTP response from a GetApiStatsAggregateWithResponse call
func ParseGetApiStatsAggregateResponse(rsp *http.Response) (*GetApiStatsAggregateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiStatsAggregateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AggregateStatsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiStatsCidCidResponse parses an HTTP response from a GetApiStatsCidCidWithResponse call
func ParseGetApiStatsCidCidResponse(rsp *http.Response) (*GetApiStatsCidCidResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiStatsCidCidResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CIDStatsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiStatsProtocolsResponse parses an HTTP response from a GetApiStatsProtocolsWithResponse call
func ParseGetApiStatsProtocolsResponse(rsp *http.Response) (*GetApiStatsProtocolsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiStatsProtocolsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProtocolStatsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
