// Package admin provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package admin

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// AllowanceGrantRequest defines model for AllowanceGrantRequest.
type AllowanceGrantRequest struct {
	Download   int       `json:"download"`
	ExpiryDate time.Time `json:"expiry_date"`
	Source     string    `json:"source"`
	Storage    int       `json:"storage"`
	Type       string    `json:"type"`
	Upload     int       `json:"upload"`
	UserId     int       `json:"user_id"`
}

// AllowanceGrantResponse defines model for AllowanceGrantResponse.
type AllowanceGrantResponse struct {
	Bytes          int       `json:"bytes"`
	BytesRemaining int       `json:"bytes_remaining"`
	BytesUsed      int       `json:"bytes_used"`
	CreatedAt      time.Time `json:"created_at"`
	ExpiryDate     time.Time `json:"expiry_date"`
	Id             int       `json:"id"`
	IsActive       bool      `json:"is_active"`
	Source         string    `json:"source"`
	Type           string    `json:"type"`
	UpdatedAt      time.Time `json:"updated_at"`
	UserId         int       `json:"user_id"`
}

// AllowanceListResponse defines model for AllowanceListResponse.
type AllowanceListResponse struct {
	Data  []AllowanceGrantResponse `json:"data"`
	Total int                      `json:"total"`
}

// CleanupRequest defines model for CleanupRequest.
type CleanupRequest struct {
	RetentionDays int `json:"retention_days"`
}

// CleanupResponse defines model for CleanupResponse.
type CleanupResponse struct {
	RecordsDeleted int `json:"records_deleted"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// PlanListResponse defines model for PlanListResponse.
type PlanListResponse struct {
	Data  []QuotaPlanResponse `json:"data"`
	Total int                 `json:"total"`
}

// QuotaPlanRequest defines model for QuotaPlanRequest.
type QuotaPlanRequest struct {
	Description        string `json:"description"`
	DownloadLimitBytes int    `json:"download_limit_bytes"`
	DownloadThreshold  int    `json:"download_threshold"`
	IsActive           bool   `json:"is_active"`
	Name               string `json:"name"`
	StorageLimitBytes  int    `json:"storage_limit_bytes"`
	StorageThreshold   int    `json:"storage_threshold"`
	UploadLimitBytes   int    `json:"upload_limit_bytes"`
	UploadThreshold    int    `json:"upload_threshold"`
	WindowDuration     int    `json:"window_duration"`
	WindowStartHour    int    `json:"window_start_hour"`
	WindowTimezone     string `json:"window_timezone"`
	WindowType         string `json:"window_type"`
}

// QuotaPlanResponse defines model for QuotaPlanResponse.
type QuotaPlanResponse struct {
	CreatedAt          time.Time `json:"created_at"`
	Description        string    `json:"description"`
	DownloadLimitBytes int       `json:"download_limit_bytes"`
	DownloadThreshold  int       `json:"download_threshold"`
	Id                 int       `json:"id"`
	IsActive           bool      `json:"is_active"`
	IsDefault          bool      `json:"is_default"`
	Name               string    `json:"name"`
	StorageLimitBytes  int       `json:"storage_limit_bytes"`
	StorageThreshold   int       `json:"storage_threshold"`
	UpdatedAt          time.Time `json:"updated_at"`
	UploadLimitBytes   int       `json:"upload_limit_bytes"`
	UploadThreshold    int       `json:"upload_threshold"`
	WindowDuration     int       `json:"window_duration"`
	WindowStartHour    int       `json:"window_start_hour"`
	WindowTimezone     string    `json:"window_timezone"`
	WindowType         string    `json:"window_type"`
}

// ReconcileRequest defines model for ReconcileRequest.
type ReconcileRequest struct {
	UserId *int `json:"user_id,omitempty"`
}

// ReconcileResponse defines model for ReconcileResponse.
type ReconcileResponse struct {
	Message        string `json:"message"`
	UsersProcessed int    `json:"users_processed"`
}

// SSLStatusInfo defines model for SSLStatusInfo.
type SSLStatusInfo struct {
	Error         *string    `json:"error,omitempty"`
	IssuedAt      *time.Time `json:"issued_at,omitempty"`
	LastUpdatedAt *time.Time `json:"last_updated_at,omitempty"`
	Status        string     `json:"status"`
}

// SystemStatsResponse defines model for SystemStatsResponse.
type SystemStatsResponse struct {
	ActiveUsers       int   `json:"active_users"`
	CurrentUsage      Usage `json:"current_usage"`
	TotalActiveGrants int   `json:"total_active_grants"`
	TotalActivePlans  int   `json:"total_active_plans"`
	TotalGrants       int   `json:"total_grants"`
	TotalPlans        int   `json:"total_plans"`
	TotalUsageBytes   int   `json:"total_usage_bytes"`
	TotalUsers        int   `json:"total_users"`
}

// Usage defines model for Usage.
type Usage struct {
	DownloadBytes int `json:"download_bytes"`
	StorageBytes  int `json:"storage_bytes"`
	UploadBytes   int `json:"upload_bytes"`
}

// UserQuotaConfigListResponse defines model for UserQuotaConfigListResponse.
type UserQuotaConfigListResponse struct {
	Data  []UserQuotaConfigResponse `json:"data"`
	Total int                       `json:"total"`
}

// UserQuotaConfigResponse defines model for UserQuotaConfigResponse.
type UserQuotaConfigResponse struct {
	CreatedAt          time.Time `json:"created_at"`
	DownloadLimitBytes *int      `json:"download_limit_bytes,omitempty"`
	DownloadThreshold  *int      `json:"download_threshold,omitempty"`
	EnforcementPolicy  string    `json:"enforcement_policy"`
	Id                 int       `json:"id"`
	QuotaPlanId        *int      `json:"quota_plan_id,omitempty"`
	StorageLimitBytes  *int      `json:"storage_limit_bytes,omitempty"`
	StorageThreshold   *int      `json:"storage_threshold,omitempty"`
	UpdatedAt          time.Time `json:"updated_at"`
	UploadLimitBytes   *int      `json:"upload_limit_bytes,omitempty"`
	UploadThreshold    *int      `json:"upload_threshold,omitempty"`
	UserId             int       `json:"user_id"`
	WindowDuration     *int      `json:"window_duration,omitempty"`
	WindowStartHour    *int      `json:"window_start_hour,omitempty"`
	WindowTimezone     *string   `json:"window_timezone,omitempty"`
	WindowType         *string   `json:"window_type,omitempty"`
}

// UserQuotaConfigUpdateRequest defines model for UserQuotaConfigUpdateRequest.
type UserQuotaConfigUpdateRequest struct {
	DownloadLimitBytes *int    `json:"download_limit_bytes,omitempty"`
	DownloadThreshold  *int    `json:"download_threshold,omitempty"`
	EnforcementPolicy  *string `json:"enforcement_policy,omitempty"`
	QuotaPlanId        *int    `json:"quota_plan_id,omitempty"`
	StorageLimitBytes  *int    `json:"storage_limit_bytes,omitempty"`
	StorageThreshold   *int    `json:"storage_threshold,omitempty"`
	UploadLimitBytes   *int    `json:"upload_limit_bytes,omitempty"`
	UploadThreshold    *int    `json:"upload_threshold,omitempty"`
	WindowDuration     *int    `json:"window_duration,omitempty"`
	WindowStartHour    *int    `json:"window_start_hour,omitempty"`
	WindowTimezone     *string `json:"window_timezone,omitempty"`
	WindowType         *string `json:"window_type,omitempty"`
}

// WebsiteResponse defines model for WebsiteResponse.
type WebsiteResponse struct {
	Created             time.Time      `json:"created"`
	DnsHostingEnabled   bool           `json:"dns_hosting_enabled"`
	DnsZoneId           *int           `json:"dns_zone_id,omitempty"`
	Domain              string         `json:"domain"`
	Expired             bool           `json:"expired"`
	Id                  int            `json:"id"`
	LastCheckedAt       *time.Time     `json:"last_checked_at,omitempty"`
	Ssl                 *SSLStatusInfo `json:"ssl,omitempty"`
	Status              string         `json:"status"`
	TargetHash          string         `json:"target_hash"`
	TargetType          string         `json:"target_type"`
	Updated             time.Time      `json:"updated"`
	ValidationExpiresAt *time.Time     `json:"validation_expires_at,omitempty"`
	ValidationToken     string         `json:"validation_token"`
}

// PostApiQuotaAllowancesJSONRequestBody defines body for PostApiQuotaAllowances for application/json ContentType.
type PostApiQuotaAllowancesJSONRequestBody = AllowanceGrantRequest

// PutApiQuotaAllowancesGrantIDJSONRequestBody defines body for PutApiQuotaAllowancesGrantID for application/json ContentType.
type PutApiQuotaAllowancesGrantIDJSONRequestBody = AllowanceGrantRequest

// PostApiQuotaPlansJSONRequestBody defines body for PostApiQuotaPlans for application/json ContentType.
type PostApiQuotaPlansJSONRequestBody = QuotaPlanRequest

// PutApiQuotaPlansPlanIDJSONRequestBody defines body for PutApiQuotaPlansPlanID for application/json ContentType.
type PutApiQuotaPlansPlanIDJSONRequestBody = QuotaPlanRequest

// PostApiQuotaSystemCleanupJSONRequestBody defines body for PostApiQuotaSystemCleanup for application/json ContentType.
type PostApiQuotaSystemCleanupJSONRequestBody = CleanupRequest

// PostApiQuotaSystemReconcileJSONRequestBody defines body for PostApiQuotaSystemReconcile for application/json ContentType.
type PostApiQuotaSystemReconcileJSONRequestBody = ReconcileRequest

// PutApiQuotaUserConfigsUserIDJSONRequestBody defines body for PutApiQuotaUserConfigsUserID for application/json ContentType.
type PutApiQuotaUserConfigsUserIDJSONRequestBody = UserQuotaConfigUpdateRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostApiIpfsWebsitesIdBlock request
	PostApiIpfsWebsitesIdBlock(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiIpfsWebsitesIdUnblock request
	PostApiIpfsWebsitesIdUnblock(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiQuotaAllowances request
	GetApiQuotaAllowances(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiQuotaAllowancesWithBody request with any body
	PostApiQuotaAllowancesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiQuotaAllowances(ctx context.Context, body PostApiQuotaAllowancesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiQuotaAllowancesGrantID request
	DeleteApiQuotaAllowancesGrantID(ctx context.Context, grantID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutApiQuotaAllowancesGrantIDWithBody request with any body
	PutApiQuotaAllowancesGrantIDWithBody(ctx context.Context, grantID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutApiQuotaAllowancesGrantID(ctx context.Context, grantID string, body PutApiQuotaAllowancesGrantIDJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiQuotaPlans request
	GetApiQuotaPlans(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiQuotaPlansWithBody request with any body
	PostApiQuotaPlansWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiQuotaPlans(ctx context.Context, body PostApiQuotaPlansJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiQuotaPlansPlanID request
	DeleteApiQuotaPlansPlanID(ctx context.Context, planID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiQuotaPlansPlanID request
	GetApiQuotaPlansPlanID(ctx context.Context, planID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutApiQuotaPlansPlanIDWithBody request with any body
	PutApiQuotaPlansPlanIDWithBody(ctx context.Context, planID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutApiQuotaPlansPlanID(ctx context.Context, planID string, body PutApiQuotaPlansPlanIDJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiQuotaPlansPlanIDDefault request
	PostApiQuotaPlansPlanIDDefault(ctx context.Context, planID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiQuotaSystemCleanupWithBody request with any body
	PostApiQuotaSystemCleanupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiQuotaSystemCleanup(ctx context.Context, body PostApiQuotaSystemCleanupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiQuotaSystemReconcileWithBody request with any body
	PostApiQuotaSystemReconcileWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiQuotaSystemReconcile(ctx context.Context, body PostApiQuotaSystemReconcileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiQuotaSystemStats request
	GetApiQuotaSystemStats(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiQuotaUserConfigs request
	GetApiQuotaUserConfigs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutApiQuotaUserConfigsUserIDWithBody request with any body
	PutApiQuotaUserConfigsUserIDWithBody(ctx context.Context, userID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutApiQuotaUserConfigsUserID(ctx context.Context, userID string, body PutApiQuotaUserConfigsUserIDJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiQuotaUserConfigsUserIDPlan request
	DeleteApiQuotaUserConfigsUserIDPlan(ctx context.Context, userID string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostApiIpfsWebsitesIdBlock(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiIpfsWebsitesIdBlockRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiIpfsWebsitesIdUnblock(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiIpfsWebsitesIdUnblockRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiQuotaAllowances(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiQuotaAllowancesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiQuotaAllowancesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiQuotaAllowancesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiQuotaAllowances(ctx context.Context, body PostApiQuotaAllowancesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiQuotaAllowancesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApiQuotaAllowancesGrantID(ctx context.Context, grantID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiQuotaAllowancesGrantIDRequest(c.Server, grantID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiQuotaAllowancesGrantIDWithBody(ctx context.Context, grantID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiQuotaAllowancesGrantIDRequestWithBody(c.Server, grantID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiQuotaAllowancesGrantID(ctx context.Context, grantID string, body PutApiQuotaAllowancesGrantIDJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiQuotaAllowancesGrantIDRequest(c.Server, grantID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiQuotaPlans(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiQuotaPlansRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiQuotaPlansWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiQuotaPlansRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiQuotaPlans(ctx context.Context, body PostApiQuotaPlansJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiQuotaPlansRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApiQuotaPlansPlanID(ctx context.Context, planID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiQuotaPlansPlanIDRequest(c.Server, planID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiQuotaPlansPlanID(ctx context.Context, planID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiQuotaPlansPlanIDRequest(c.Server, planID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiQuotaPlansPlanIDWithBody(ctx context.Context, planID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiQuotaPlansPlanIDRequestWithBody(c.Server, planID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiQuotaPlansPlanID(ctx context.Context, planID string, body PutApiQuotaPlansPlanIDJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiQuotaPlansPlanIDRequest(c.Server, planID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiQuotaPlansPlanIDDefault(ctx context.Context, planID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiQuotaPlansPlanIDDefaultRequest(c.Server, planID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiQuotaSystemCleanupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiQuotaSystemCleanupRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiQuotaSystemCleanup(ctx context.Context, body PostApiQuotaSystemCleanupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiQuotaSystemCleanupRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiQuotaSystemReconcileWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiQuotaSystemReconcileRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiQuotaSystemReconcile(ctx context.Context, body PostApiQuotaSystemReconcileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiQuotaSystemReconcileRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiQuotaSystemStats(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiQuotaSystemStatsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiQuotaUserConfigs(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiQuotaUserConfigsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiQuotaUserConfigsUserIDWithBody(ctx context.Context, userID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiQuotaUserConfigsUserIDRequestWithBody(c.Server, userID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiQuotaUserConfigsUserID(ctx context.Context, userID string, body PutApiQuotaUserConfigsUserIDJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiQuotaUserConfigsUserIDRequest(c.Server, userID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApiQuotaUserConfigsUserIDPlan(ctx context.Context, userID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiQuotaUserConfigsUserIDPlanRequest(c.Server, userID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostApiIpfsWebsitesIdBlockRequest generates requests for PostApiIpfsWebsitesIdBlock
func NewPostApiIpfsWebsitesIdBlockRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/ipfs/websites/%s/block", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiIpfsWebsitesIdUnblockRequest generates requests for PostApiIpfsWebsitesIdUnblock
func NewPostApiIpfsWebsitesIdUnblockRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/ipfs/websites/%s/unblock", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiQuotaAllowancesRequest generates requests for GetApiQuotaAllowances
func NewGetApiQuotaAllowancesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/allowances")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiQuotaAllowancesRequest calls the generic PostApiQuotaAllowances builder with application/json body
func NewPostApiQuotaAllowancesRequest(server string, body PostApiQuotaAllowancesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiQuotaAllowancesRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiQuotaAllowancesRequestWithBody generates requests for PostApiQuotaAllowances with any type of body
func NewPostApiQuotaAllowancesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/allowances")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteApiQuotaAllowancesGrantIDRequest generates requests for DeleteApiQuotaAllowancesGrantID
func NewDeleteApiQuotaAllowancesGrantIDRequest(server string, grantID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "grantID", runtime.ParamLocationPath, grantID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/allowances/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutApiQuotaAllowancesGrantIDRequest calls the generic PutApiQuotaAllowancesGrantID builder with application/json body
func NewPutApiQuotaAllowancesGrantIDRequest(server string, grantID string, body PutApiQuotaAllowancesGrantIDJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutApiQuotaAllowancesGrantIDRequestWithBody(server, grantID, "application/json", bodyReader)
}

// NewPutApiQuotaAllowancesGrantIDRequestWithBody generates requests for PutApiQuotaAllowancesGrantID with any type of body
func NewPutApiQuotaAllowancesGrantIDRequestWithBody(server string, grantID string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "grantID", runtime.ParamLocationPath, grantID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/allowances/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiQuotaPlansRequest generates requests for GetApiQuotaPlans
func NewGetApiQuotaPlansRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/plans")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiQuotaPlansRequest calls the generic PostApiQuotaPlans builder with application/json body
func NewPostApiQuotaPlansRequest(server string, body PostApiQuotaPlansJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiQuotaPlansRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiQuotaPlansRequestWithBody generates requests for PostApiQuotaPlans with any type of body
func NewPostApiQuotaPlansRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/plans")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteApiQuotaPlansPlanIDRequest generates requests for DeleteApiQuotaPlansPlanID
func NewDeleteApiQuotaPlansPlanIDRequest(server string, planID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "planID", runtime.ParamLocationPath, planID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/plans/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiQuotaPlansPlanIDRequest generates requests for GetApiQuotaPlansPlanID
func NewGetApiQuotaPlansPlanIDRequest(server string, planID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "planID", runtime.ParamLocationPath, planID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/plans/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutApiQuotaPlansPlanIDRequest calls the generic PutApiQuotaPlansPlanID builder with application/json body
func NewPutApiQuotaPlansPlanIDRequest(server string, planID string, body PutApiQuotaPlansPlanIDJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutApiQuotaPlansPlanIDRequestWithBody(server, planID, "application/json", bodyReader)
}

// NewPutApiQuotaPlansPlanIDRequestWithBody generates requests for PutApiQuotaPlansPlanID with any type of body
func NewPutApiQuotaPlansPlanIDRequestWithBody(server string, planID string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "planID", runtime.ParamLocationPath, planID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/plans/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApiQuotaPlansPlanIDDefaultRequest generates requests for PostApiQuotaPlansPlanIDDefault
func NewPostApiQuotaPlansPlanIDDefaultRequest(server string, planID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "planID", runtime.ParamLocationPath, planID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/plans/%s/default", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiQuotaSystemCleanupRequest calls the generic PostApiQuotaSystemCleanup builder with application/json body
func NewPostApiQuotaSystemCleanupRequest(server string, body PostApiQuotaSystemCleanupJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiQuotaSystemCleanupRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiQuotaSystemCleanupRequestWithBody generates requests for PostApiQuotaSystemCleanup with any type of body
func NewPostApiQuotaSystemCleanupRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/system/cleanup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApiQuotaSystemReconcileRequest calls the generic PostApiQuotaSystemReconcile builder with application/json body
func NewPostApiQuotaSystemReconcileRequest(server string, body PostApiQuotaSystemReconcileJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiQuotaSystemReconcileRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiQuotaSystemReconcileRequestWithBody generates requests for PostApiQuotaSystemReconcile with any type of body
func NewPostApiQuotaSystemReconcileRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/system/reconcile")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiQuotaSystemStatsRequest generates requests for GetApiQuotaSystemStats
func NewGetApiQuotaSystemStatsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/system/stats")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiQuotaUserConfigsRequest generates requests for GetApiQuotaUserConfigs
func NewGetApiQuotaUserConfigsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/user-configs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutApiQuotaUserConfigsUserIDRequest calls the generic PutApiQuotaUserConfigsUserID builder with application/json body
func NewPutApiQuotaUserConfigsUserIDRequest(server string, userID string, body PutApiQuotaUserConfigsUserIDJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutApiQuotaUserConfigsUserIDRequestWithBody(server, userID, "application/json", bodyReader)
}

// NewPutApiQuotaUserConfigsUserIDRequestWithBody generates requests for PutApiQuotaUserConfigsUserID with any type of body
func NewPutApiQuotaUserConfigsUserIDRequestWithBody(server string, userID string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "userID", runtime.ParamLocationPath, userID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/user-configs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteApiQuotaUserConfigsUserIDPlanRequest generates requests for DeleteApiQuotaUserConfigsUserIDPlan
func NewDeleteApiQuotaUserConfigsUserIDPlanRequest(server string, userID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "userID", runtime.ParamLocationPath, userID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/quota/user-configs/%s/plan", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostApiIpfsWebsitesIdBlockWithResponse request
	PostApiIpfsWebsitesIdBlockWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*PostApiIpfsWebsitesIdBlockResponse, error)

	// PostApiIpfsWebsitesIdUnblockWithResponse request
	PostApiIpfsWebsitesIdUnblockWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*PostApiIpfsWebsitesIdUnblockResponse, error)

	// GetApiQuotaAllowancesWithResponse request
	GetApiQuotaAllowancesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiQuotaAllowancesResponse, error)

	// PostApiQuotaAllowancesWithBodyWithResponse request with any body
	PostApiQuotaAllowancesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiQuotaAllowancesResponse, error)

	PostApiQuotaAllowancesWithResponse(ctx context.Context, body PostApiQuotaAllowancesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiQuotaAllowancesResponse, error)

	// DeleteApiQuotaAllowancesGrantIDWithResponse request
	DeleteApiQuotaAllowancesGrantIDWithResponse(ctx context.Context, grantID string, reqEditors ...RequestEditorFn) (*DeleteApiQuotaAllowancesGrantIDResponse, error)

	// PutApiQuotaAllowancesGrantIDWithBodyWithResponse request with any body
	PutApiQuotaAllowancesGrantIDWithBodyWithResponse(ctx context.Context, grantID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiQuotaAllowancesGrantIDResponse, error)

	PutApiQuotaAllowancesGrantIDWithResponse(ctx context.Context, grantID string, body PutApiQuotaAllowancesGrantIDJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiQuotaAllowancesGrantIDResponse, error)

	// GetApiQuotaPlansWithResponse request
	GetApiQuotaPlansWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiQuotaPlansResponse, error)

	// PostApiQuotaPlansWithBodyWithResponse request with any body
	PostApiQuotaPlansWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiQuotaPlansResponse, error)

	PostApiQuotaPlansWithResponse(ctx context.Context, body PostApiQuotaPlansJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiQuotaPlansResponse, error)

	// DeleteApiQuotaPlansPlanIDWithResponse request
	DeleteApiQuotaPlansPlanIDWithResponse(ctx context.Context, planID string, reqEditors ...RequestEditorFn) (*DeleteApiQuotaPlansPlanIDResponse, error)

	// GetApiQuotaPlansPlanIDWithResponse request
	GetApiQuotaPlansPlanIDWithResponse(ctx context.Context, planID string, reqEditors ...RequestEditorFn) (*GetApiQuotaPlansPlanIDResponse, error)

	// PutApiQuotaPlansPlanIDWithBodyWithResponse request with any body
	PutApiQuotaPlansPlanIDWithBodyWithResponse(ctx context.Context, planID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiQuotaPlansPlanIDResponse, error)

	PutApiQuotaPlansPlanIDWithResponse(ctx context.Context, planID string, body PutApiQuotaPlansPlanIDJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiQuotaPlansPlanIDResponse, error)

	// PostApiQuotaPlansPlanIDDefaultWithResponse request
	PostApiQuotaPlansPlanIDDefaultWithResponse(ctx context.Context, planID string, reqEditors ...RequestEditorFn) (*PostApiQuotaPlansPlanIDDefaultResponse, error)

	// PostApiQuotaSystemCleanupWithBodyWithResponse request with any body
	PostApiQuotaSystemCleanupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiQuotaSystemCleanupResponse, error)

	PostApiQuotaSystemCleanupWithResponse(ctx context.Context, body PostApiQuotaSystemCleanupJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiQuotaSystemCleanupResponse, error)

	// PostApiQuotaSystemReconcileWithBodyWithResponse request with any body
	PostApiQuotaSystemReconcileWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiQuotaSystemReconcileResponse, error)

	PostApiQuotaSystemReconcileWithResponse(ctx context.Context, body PostApiQuotaSystemReconcileJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiQuotaSystemReconcileResponse, error)

	// GetApiQuotaSystemStatsWithResponse request
	GetApiQuotaSystemStatsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiQuotaSystemStatsResponse, error)

	// GetApiQuotaUserConfigsWithResponse request
	GetApiQuotaUserConfigsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiQuotaUserConfigsResponse, error)

	// PutApiQuotaUserConfigsUserIDWithBodyWithResponse request with any body
	PutApiQuotaUserConfigsUserIDWithBodyWithResponse(ctx context.Context, userID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiQuotaUserConfigsUserIDResponse, error)

	PutApiQuotaUserConfigsUserIDWithResponse(ctx context.Context, userID string, body PutApiQuotaUserConfigsUserIDJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiQuotaUserConfigsUserIDResponse, error)

	// DeleteApiQuotaUserConfigsUserIDPlanWithResponse request
	DeleteApiQuotaUserConfigsUserIDPlanWithResponse(ctx context.Context, userID string, reqEditors ...RequestEditorFn) (*DeleteApiQuotaUserConfigsUserIDPlanResponse, error)
}

type PostApiIpfsWebsitesIdBlockResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *WebsiteResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiIpfsWebsitesIdBlockResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiIpfsWebsitesIdBlockResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiIpfsWebsitesIdUnblockResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *WebsiteResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiIpfsWebsitesIdUnblockResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiIpfsWebsitesIdUnblockResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiQuotaAllowancesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AllowanceListResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiQuotaAllowancesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiQuotaAllowancesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiQuotaAllowancesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ErrorResponse
	JSON201      *AllowanceGrantResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiQuotaAllowancesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiQuotaAllowancesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteApiQuotaAllowancesGrantIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteApiQuotaAllowancesGrantIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiQuotaAllowancesGrantIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutApiQuotaAllowancesGrantIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AllowanceGrantResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutApiQuotaAllowancesGrantIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutApiQuotaAllowancesGrantIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiQuotaPlansResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PlanListResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiQuotaPlansResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiQuotaPlansResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiQuotaPlansResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ErrorResponse
	JSON201      *QuotaPlanResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiQuotaPlansResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiQuotaPlansResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteApiQuotaPlansPlanIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteApiQuotaPlansPlanIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiQuotaPlansPlanIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiQuotaPlansPlanIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *QuotaPlanResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiQuotaPlansPlanIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiQuotaPlansPlanIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutApiQuotaPlansPlanIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *QuotaPlanResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutApiQuotaPlansPlanIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutApiQuotaPlansPlanIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiQuotaPlansPlanIDDefaultResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiQuotaPlansPlanIDDefaultResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiQuotaPlansPlanIDDefaultResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiQuotaSystemCleanupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CleanupResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiQuotaSystemCleanupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiQuotaSystemCleanupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiQuotaSystemReconcileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ReconcileResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiQuotaSystemReconcileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiQuotaSystemReconcileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiQuotaSystemStatsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SystemStatsResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiQuotaSystemStatsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiQuotaSystemStatsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiQuotaUserConfigsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserQuotaConfigListResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiQuotaUserConfigsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiQuotaUserConfigsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutApiQuotaUserConfigsUserIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserQuotaConfigResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutApiQuotaUserConfigsUserIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutApiQuotaUserConfigsUserIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteApiQuotaUserConfigsUserIDPlanResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteApiQuotaUserConfigsUserIDPlanResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiQuotaUserConfigsUserIDPlanResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostApiIpfsWebsitesIdBlockWithResponse request returning *PostApiIpfsWebsitesIdBlockResponse
func (c *ClientWithResponses) PostApiIpfsWebsitesIdBlockWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*PostApiIpfsWebsitesIdBlockResponse, error) {
	rsp, err := c.PostApiIpfsWebsitesIdBlock(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiIpfsWebsitesIdBlockResponse(rsp)
}

// PostApiIpfsWebsitesIdUnblockWithResponse request returning *PostApiIpfsWebsitesIdUnblockResponse
func (c *ClientWithResponses) PostApiIpfsWebsitesIdUnblockWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*PostApiIpfsWebsitesIdUnblockResponse, error) {
	rsp, err := c.PostApiIpfsWebsitesIdUnblock(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiIpfsWebsitesIdUnblockResponse(rsp)
}

// GetApiQuotaAllowancesWithResponse request returning *GetApiQuotaAllowancesResponse
func (c *ClientWithResponses) GetApiQuotaAllowancesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiQuotaAllowancesResponse, error) {
	rsp, err := c.GetApiQuotaAllowances(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiQuotaAllowancesResponse(rsp)
}

// PostApiQuotaAllowancesWithBodyWithResponse request with arbitrary body returning *PostApiQuotaAllowancesResponse
func (c *ClientWithResponses) PostApiQuotaAllowancesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiQuotaAllowancesResponse, error) {
	rsp, err := c.PostApiQuotaAllowancesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiQuotaAllowancesResponse(rsp)
}

func (c *ClientWithResponses) PostApiQuotaAllowancesWithResponse(ctx context.Context, body PostApiQuotaAllowancesJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiQuotaAllowancesResponse, error) {
	rsp, err := c.PostApiQuotaAllowances(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiQuotaAllowancesResponse(rsp)
}

// DeleteApiQuotaAllowancesGrantIDWithResponse request returning *DeleteApiQuotaAllowancesGrantIDResponse
func (c *ClientWithResponses) DeleteApiQuotaAllowancesGrantIDWithResponse(ctx context.Context, grantID string, reqEditors ...RequestEditorFn) (*DeleteApiQuotaAllowancesGrantIDResponse, error) {
	rsp, err := c.DeleteApiQuotaAllowancesGrantID(ctx, grantID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiQuotaAllowancesGrantIDResponse(rsp)
}

// PutApiQuotaAllowancesGrantIDWithBodyWithResponse request with arbitrary body returning *PutApiQuotaAllowancesGrantIDResponse
func (c *ClientWithResponses) PutApiQuotaAllowancesGrantIDWithBodyWithResponse(ctx context.Context, grantID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiQuotaAllowancesGrantIDResponse, error) {
	rsp, err := c.PutApiQuotaAllowancesGrantIDWithBody(ctx, grantID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiQuotaAllowancesGrantIDResponse(rsp)
}

func (c *ClientWithResponses) PutApiQuotaAllowancesGrantIDWithResponse(ctx context.Context, grantID string, body PutApiQuotaAllowancesGrantIDJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiQuotaAllowancesGrantIDResponse, error) {
	rsp, err := c.PutApiQuotaAllowancesGrantID(ctx, grantID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiQuotaAllowancesGrantIDResponse(rsp)
}

// GetApiQuotaPlansWithResponse request returning *GetApiQuotaPlansResponse
func (c *ClientWithResponses) GetApiQuotaPlansWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiQuotaPlansResponse, error) {
	rsp, err := c.GetApiQuotaPlans(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiQuotaPlansResponse(rsp)
}

// PostApiQuotaPlansWithBodyWithResponse request with arbitrary body returning *PostApiQuotaPlansResponse
func (c *ClientWithResponses) PostApiQuotaPlansWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiQuotaPlansResponse, error) {
	rsp, err := c.PostApiQuotaPlansWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiQuotaPlansResponse(rsp)
}

func (c *ClientWithResponses) PostApiQuotaPlansWithResponse(ctx context.Context, body PostApiQuotaPlansJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiQuotaPlansResponse, error) {
	rsp, err := c.PostApiQuotaPlans(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiQuotaPlansResponse(rsp)
}

// DeleteApiQuotaPlansPlanIDWithResponse request returning *DeleteApiQuotaPlansPlanIDResponse
func (c *ClientWithResponses) DeleteApiQuotaPlansPlanIDWithResponse(ctx context.Context, planID string, reqEditors ...RequestEditorFn) (*DeleteApiQuotaPlansPlanIDResponse, error) {
	rsp, err := c.DeleteApiQuotaPlansPlanID(ctx, planID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiQuotaPlansPlanIDResponse(rsp)
}

// GetApiQuotaPlansPlanIDWithResponse request returning *GetApiQuotaPlansPlanIDResponse
func (c *ClientWithResponses) GetApiQuotaPlansPlanIDWithResponse(ctx context.Context, planID string, reqEditors ...RequestEditorFn) (*GetApiQuotaPlansPlanIDResponse, error) {
	rsp, err := c.GetApiQuotaPlansPlanID(ctx, planID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiQuotaPlansPlanIDResponse(rsp)
}

// PutApiQuotaPlansPlanIDWithBodyWithResponse request with arbitrary body returning *PutApiQuotaPlansPlanIDResponse
func (c *ClientWithResponses) PutApiQuotaPlansPlanIDWithBodyWithResponse(ctx context.Context, planID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiQuotaPlansPlanIDResponse, error) {
	rsp, err := c.PutApiQuotaPlansPlanIDWithBody(ctx, planID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiQuotaPlansPlanIDResponse(rsp)
}

func (c *ClientWithResponses) PutApiQuotaPlansPlanIDWithResponse(ctx context.Context, planID string, body PutApiQuotaPlansPlanIDJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiQuotaPlansPlanIDResponse, error) {
	rsp, err := c.PutApiQuotaPlansPlanID(ctx, planID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiQuotaPlansPlanIDResponse(rsp)
}

// PostApiQuotaPlansPlanIDDefaultWithResponse request returning *PostApiQuotaPlansPlanIDDefaultResponse
func (c *ClientWithResponses) PostApiQuotaPlansPlanIDDefaultWithResponse(ctx context.Context, planID string, reqEditors ...RequestEditorFn) (*PostApiQuotaPlansPlanIDDefaultResponse, error) {
	rsp, err := c.PostApiQuotaPlansPlanIDDefault(ctx, planID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiQuotaPlansPlanIDDefaultResponse(rsp)
}

// PostApiQuotaSystemCleanupWithBodyWithResponse request with arbitrary body returning *PostApiQuotaSystemCleanupResponse
func (c *ClientWithResponses) PostApiQuotaSystemCleanupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiQuotaSystemCleanupResponse, error) {
	rsp, err := c.PostApiQuotaSystemCleanupWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiQuotaSystemCleanupResponse(rsp)
}

func (c *ClientWithResponses) PostApiQuotaSystemCleanupWithResponse(ctx context.Context, body PostApiQuotaSystemCleanupJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiQuotaSystemCleanupResponse, error) {
	rsp, err := c.PostApiQuotaSystemCleanup(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiQuotaSystemCleanupResponse(rsp)
}

// PostApiQuotaSystemReconcileWithBodyWithResponse request with arbitrary body returning *PostApiQuotaSystemReconcileResponse
func (c *ClientWithResponses) PostApiQuotaSystemReconcileWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiQuotaSystemReconcileResponse, error) {
	rsp, err := c.PostApiQuotaSystemReconcileWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiQuotaSystemReconcileResponse(rsp)
}

func (c *ClientWithResponses) PostApiQuotaSystemReconcileWithResponse(ctx context.Context, body PostApiQuotaSystemReconcileJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiQuotaSystemReconcileResponse, error) {
	rsp, err := c.PostApiQuotaSystemReconcile(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiQuotaSystemReconcileResponse(rsp)
}

// GetApiQuotaSystemStatsWithResponse request returning *GetApiQuotaSystemStatsResponse
func (c *ClientWithResponses) GetApiQuotaSystemStatsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiQuotaSystemStatsResponse, error) {
	rsp, err := c.GetApiQuotaSystemStats(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiQuotaSystemStatsResponse(rsp)
}

// GetApiQuotaUserConfigsWithResponse request returning *GetApiQuotaUserConfigsResponse
func (c *ClientWithResponses) GetApiQuotaUserConfigsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiQuotaUserConfigsResponse, error) {
	rsp, err := c.GetApiQuotaUserConfigs(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiQuotaUserConfigsResponse(rsp)
}

// PutApiQuotaUserConfigsUserIDWithBodyWithResponse request with arbitrary body returning *PutApiQuotaUserConfigsUserIDResponse
func (c *ClientWithResponses) PutApiQuotaUserConfigsUserIDWithBodyWithResponse(ctx context.Context, userID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiQuotaUserConfigsUserIDResponse, error) {
	rsp, err := c.PutApiQuotaUserConfigsUserIDWithBody(ctx, userID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiQuotaUserConfigsUserIDResponse(rsp)
}

func (c *ClientWithResponses) PutApiQuotaUserConfigsUserIDWithResponse(ctx context.Context, userID string, body PutApiQuotaUserConfigsUserIDJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiQuotaUserConfigsUserIDResponse, error) {
	rsp, err := c.PutApiQuotaUserConfigsUserID(ctx, userID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiQuotaUserConfigsUserIDResponse(rsp)
}

// DeleteApiQuotaUserConfigsUserIDPlanWithResponse request returning *DeleteApiQuotaUserConfigsUserIDPlanResponse
func (c *ClientWithResponses) DeleteApiQuotaUserConfigsUserIDPlanWithResponse(ctx context.Context, userID string, reqEditors ...RequestEditorFn) (*DeleteApiQuotaUserConfigsUserIDPlanResponse, error) {
	rsp, err := c.DeleteApiQuotaUserConfigsUserIDPlan(ctx, userID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiQuotaUserConfigsUserIDPlanResponse(rsp)
}

// ParsePostApiIpfsWebsitesIdBlockResponse parses an HTTP response from a PostApiIpfsWebsitesIdBlockWithResponse call
func ParsePostApiIpfsWebsitesIdBlockResponse(rsp *http.Response) (*PostApiIpfsWebsitesIdBlockResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiIpfsWebsitesIdBlockResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WebsiteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiIpfsWebsitesIdUnblockResponse parses an HTTP response from a PostApiIpfsWebsitesIdUnblockWithResponse call
func ParsePostApiIpfsWebsitesIdUnblockResponse(rsp *http.Response) (*PostApiIpfsWebsitesIdUnblockResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiIpfsWebsitesIdUnblockResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WebsiteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiQuotaAllowancesResponse parses an HTTP response from a GetApiQuotaAllowancesWithResponse call
func ParseGetApiQuotaAllowancesResponse(rsp *http.Response) (*GetApiQuotaAllowancesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiQuotaAllowancesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AllowanceListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiQuotaAllowancesResponse parses an HTTP response from a PostApiQuotaAllowancesWithResponse call
func ParsePostApiQuotaAllowancesResponse(rsp *http.Response) (*PostApiQuotaAllowancesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiQuotaAllowancesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest AllowanceGrantResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteApiQuotaAllowancesGrantIDResponse parses an HTTP response from a DeleteApiQuotaAllowancesGrantIDWithResponse call
func ParseDeleteApiQuotaAllowancesGrantIDResponse(rsp *http.Response) (*DeleteApiQuotaAllowancesGrantIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiQuotaAllowancesGrantIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutApiQuotaAllowancesGrantIDResponse parses an HTTP response from a PutApiQuotaAllowancesGrantIDWithResponse call
func ParsePutApiQuotaAllowancesGrantIDResponse(rsp *http.Response) (*PutApiQuotaAllowancesGrantIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutApiQuotaAllowancesGrantIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AllowanceGrantResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiQuotaPlansResponse parses an HTTP response from a GetApiQuotaPlansWithResponse call
func ParseGetApiQuotaPlansResponse(rsp *http.Response) (*GetApiQuotaPlansResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiQuotaPlansResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PlanListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiQuotaPlansResponse parses an HTTP response from a PostApiQuotaPlansWithResponse call
func ParsePostApiQuotaPlansResponse(rsp *http.Response) (*PostApiQuotaPlansResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiQuotaPlansResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest QuotaPlanResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteApiQuotaPlansPlanIDResponse parses an HTTP response from a DeleteApiQuotaPlansPlanIDWithResponse call
func ParseDeleteApiQuotaPlansPlanIDResponse(rsp *http.Response) (*DeleteApiQuotaPlansPlanIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiQuotaPlansPlanIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiQuotaPlansPlanIDResponse parses an HTTP response from a GetApiQuotaPlansPlanIDWithResponse call
func ParseGetApiQuotaPlansPlanIDResponse(rsp *http.Response) (*GetApiQuotaPlansPlanIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiQuotaPlansPlanIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest QuotaPlanResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutApiQuotaPlansPlanIDResponse parses an HTTP response from a PutApiQuotaPlansPlanIDWithResponse call
func ParsePutApiQuotaPlansPlanIDResponse(rsp *http.Response) (*PutApiQuotaPlansPlanIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutApiQuotaPlansPlanIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest QuotaPlanResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiQuotaPlansPlanIDDefaultResponse parses an HTTP response from a PostApiQuotaPlansPlanIDDefaultWithResponse call
func ParsePostApiQuotaPlansPlanIDDefaultResponse(rsp *http.Response) (*PostApiQuotaPlansPlanIDDefaultResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiQuotaPlansPlanIDDefaultResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiQuotaSystemCleanupResponse parses an HTTP response from a PostApiQuotaSystemCleanupWithResponse call
func ParsePostApiQuotaSystemCleanupResponse(rsp *http.Response) (*PostApiQuotaSystemCleanupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiQuotaSystemCleanupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CleanupResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiQuotaSystemReconcileResponse parses an HTTP response from a PostApiQuotaSystemReconcileWithResponse call
func ParsePostApiQuotaSystemReconcileResponse(rsp *http.Response) (*PostApiQuotaSystemReconcileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiQuotaSystemReconcileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReconcileResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiQuotaSystemStatsResponse parses an HTTP response from a GetApiQuotaSystemStatsWithResponse call
func ParseGetApiQuotaSystemStatsResponse(rsp *http.Response) (*GetApiQuotaSystemStatsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiQuotaSystemStatsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SystemStatsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiQuotaUserConfigsResponse parses an HTTP response from a GetApiQuotaUserConfigsWithResponse call
func ParseGetApiQuotaUserConfigsResponse(rsp *http.Response) (*GetApiQuotaUserConfigsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiQuotaUserConfigsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserQuotaConfigListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutApiQuotaUserConfigsUserIDResponse parses an HTTP response from a PutApiQuotaUserConfigsUserIDWithResponse call
func ParsePutApiQuotaUserConfigsUserIDResponse(rsp *http.Response) (*PutApiQuotaUserConfigsUserIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutApiQuotaUserConfigsUserIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserQuotaConfigResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteApiQuotaUserConfigsUserIDPlanResponse parses an HTTP response from a DeleteApiQuotaUserConfigsUserIDPlanWithResponse call
func ParseDeleteApiQuotaUserConfigsUserIDPlanResponse(rsp *http.Response) (*DeleteApiQuotaUserConfigsUserIDPlanResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiQuotaUserConfigsUserIDPlanResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
