// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	account "go.lumeweb.com/portal-sdk"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountAPI is an autogenerated mock type for the AccountAPI type
type MockAccountAPI struct {
	mock.Mock
}

type MockAccountAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountAPI) EXPECT() *MockAccountAPI_Expecter {
	return &MockAccountAPI_Expecter{mock: &_m.Mock}
}

// AbortSubscriptionCancellation provides a mock function with given fields: ctx
func (_m *MockAccountAPI) AbortSubscriptionCancellation(ctx context.Context) (*account.ManagementResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AbortSubscriptionCancellation")
	}

	var r0 *account.ManagementResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*account.ManagementResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *account.ManagementResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ManagementResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_AbortSubscriptionCancellation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortSubscriptionCancellation'
type MockAccountAPI_AbortSubscriptionCancellation_Call struct {
	*mock.Call
}

// AbortSubscriptionCancellation is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) AbortSubscriptionCancellation(ctx interface{}) *MockAccountAPI_AbortSubscriptionCancellation_Call {
	return &MockAccountAPI_AbortSubscriptionCancellation_Call{Call: _e.mock.On("AbortSubscriptionCancellation", ctx)}
}

func (_c *MockAccountAPI_AbortSubscriptionCancellation_Call) Run(run func(ctx context.Context)) *MockAccountAPI_AbortSubscriptionCancellation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_AbortSubscriptionCancellation_Call) Return(_a0 *account.ManagementResult, _a1 error) *MockAccountAPI_AbortSubscriptionCancellation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_AbortSubscriptionCancellation_Call) RunAndReturn(run func(context.Context) (*account.ManagementResult, error)) *MockAccountAPI_AbortSubscriptionCancellation_Call {
	_c.Call.Return(run)
	return _c
}

// CancelSubscription provides a mock function with given fields: ctx
func (_m *MockAccountAPI) CancelSubscription(ctx context.Context) (*account.ManagementResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CancelSubscription")
	}

	var r0 *account.ManagementResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*account.ManagementResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *account.ManagementResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ManagementResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_CancelSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelSubscription'
type MockAccountAPI_CancelSubscription_Call struct {
	*mock.Call
}

// CancelSubscription is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) CancelSubscription(ctx interface{}) *MockAccountAPI_CancelSubscription_Call {
	return &MockAccountAPI_CancelSubscription_Call{Call: _e.mock.On("CancelSubscription", ctx)}
}

func (_c *MockAccountAPI_CancelSubscription_Call) Run(run func(ctx context.Context)) *MockAccountAPI_CancelSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_CancelSubscription_Call) Return(_a0 *account.ManagementResult, _a1 error) *MockAccountAPI_CancelSubscription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_CancelSubscription_Call) RunAndReturn(run func(context.Context) (*account.ManagementResult, error)) *MockAccountAPI_CancelSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// ChangePlan provides a mock function with given fields: ctx, periodID
func (_m *MockAccountAPI) ChangePlan(ctx context.Context, periodID int) (*account.ManagementResult, error) {
	ret := _m.Called(ctx, periodID)

	if len(ret) == 0 {
		panic("no return value specified for ChangePlan")
	}

	var r0 *account.ManagementResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*account.ManagementResult, error)); ok {
		return rf(ctx, periodID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *account.ManagementResult); ok {
		r0 = rf(ctx, periodID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ManagementResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, periodID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_ChangePlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePlan'
type MockAccountAPI_ChangePlan_Call struct {
	*mock.Call
}

// ChangePlan is a helper method to define mock.On call
//   - ctx context.Context
//   - periodID int
func (_e *MockAccountAPI_Expecter) ChangePlan(ctx interface{}, periodID interface{}) *MockAccountAPI_ChangePlan_Call {
	return &MockAccountAPI_ChangePlan_Call{Call: _e.mock.On("ChangePlan", ctx, periodID)}
}

func (_c *MockAccountAPI_ChangePlan_Call) Run(run func(ctx context.Context, periodID int)) *MockAccountAPI_ChangePlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAccountAPI_ChangePlan_Call) Return(_a0 *account.ManagementResult, _a1 error) *MockAccountAPI_ChangePlan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_ChangePlan_Call) RunAndReturn(run func(context.Context, int) (*account.ManagementResult, error)) *MockAccountAPI_ChangePlan_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmPasswordReset provides a mock function with given fields: ctx, email, token, newPassword
func (_m *MockAccountAPI) ConfirmPasswordReset(ctx context.Context, email string, token string, newPassword string) error {
	ret := _m.Called(ctx, email, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, email, token, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_ConfirmPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmPasswordReset'
type MockAccountAPI_ConfirmPasswordReset_Call struct {
	*mock.Call
}

// ConfirmPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - token string
//   - newPassword string
func (_e *MockAccountAPI_Expecter) ConfirmPasswordReset(ctx interface{}, email interface{}, token interface{}, newPassword interface{}) *MockAccountAPI_ConfirmPasswordReset_Call {
	return &MockAccountAPI_ConfirmPasswordReset_Call{Call: _e.mock.On("ConfirmPasswordReset", ctx, email, token, newPassword)}
}

func (_c *MockAccountAPI_ConfirmPasswordReset_Call) Run(run func(ctx context.Context, email string, token string, newPassword string)) *MockAccountAPI_ConfirmPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAccountAPI_ConfirmPasswordReset_Call) Return(_a0 error) *MockAccountAPI_ConfirmPasswordReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_ConfirmPasswordReset_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockAccountAPI_ConfirmPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAPIKey provides a mock function with given fields: ctx, name
func (_m *MockAccountAPI) CreateAPIKey(ctx context.Context, name string) (*account.APIKey, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateAPIKey")
	}

	var r0 *account.APIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*account.APIKey, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *account.APIKey); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_CreateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAPIKey'
type MockAccountAPI_CreateAPIKey_Call struct {
	*mock.Call
}

// CreateAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAccountAPI_Expecter) CreateAPIKey(ctx interface{}, name interface{}) *MockAccountAPI_CreateAPIKey_Call {
	return &MockAccountAPI_CreateAPIKey_Call{Call: _e.mock.On("CreateAPIKey", ctx, name)}
}

func (_c *MockAccountAPI_CreateAPIKey_Call) Run(run func(ctx context.Context, name string)) *MockAccountAPI_CreateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountAPI_CreateAPIKey_Call) Return(_a0 *account.APIKey, _a1 error) *MockAccountAPI_CreateAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_CreateAPIKey_Call) RunAndReturn(run func(context.Context, string) (*account.APIKey, error)) *MockAccountAPI_CreateAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAPIKey provides a mock function with given fields: ctx, keyID
func (_m *MockAccountAPI) DeleteAPIKey(ctx context.Context, keyID string) error {
	ret := _m.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAPIKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, keyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_DeleteAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAPIKey'
type MockAccountAPI_DeleteAPIKey_Call struct {
	*mock.Call
}

// DeleteAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
func (_e *MockAccountAPI_Expecter) DeleteAPIKey(ctx interface{}, keyID interface{}) *MockAccountAPI_DeleteAPIKey_Call {
	return &MockAccountAPI_DeleteAPIKey_Call{Call: _e.mock.On("DeleteAPIKey", ctx, keyID)}
}

func (_c *MockAccountAPI_DeleteAPIKey_Call) Run(run func(ctx context.Context, keyID string)) *MockAccountAPI_DeleteAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountAPI_DeleteAPIKey_Call) Return(_a0 error) *MockAccountAPI_DeleteAPIKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_DeleteAPIKey_Call) RunAndReturn(run func(context.Context, string) error) *MockAccountAPI_DeleteAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function with given fields: ctx
func (_m *MockAccountAPI) DeleteAccount(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockAccountAPI_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) DeleteAccount(ctx interface{}) *MockAccountAPI_DeleteAccount_Call {
	return &MockAccountAPI_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx)}
}

func (_c *MockAccountAPI_DeleteAccount_Call) Run(run func(ctx context.Context)) *MockAccountAPI_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_DeleteAccount_Call) Return(_a0 error) *MockAccountAPI_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_DeleteAccount_Call) RunAndReturn(run func(context.Context) error) *MockAccountAPI_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DisableOTP provides a mock function with given fields: ctx, password
func (_m *MockAccountAPI) DisableOTP(ctx context.Context, password string) error {
	ret := _m.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for DisableOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_DisableOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableOTP'
type MockAccountAPI_DisableOTP_Call struct {
	*mock.Call
}

// DisableOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
func (_e *MockAccountAPI_Expecter) DisableOTP(ctx interface{}, password interface{}) *MockAccountAPI_DisableOTP_Call {
	return &MockAccountAPI_DisableOTP_Call{Call: _e.mock.On("DisableOTP", ctx, password)}
}

func (_c *MockAccountAPI_DisableOTP_Call) Run(run func(ctx context.Context, password string)) *MockAccountAPI_DisableOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountAPI_DisableOTP_Call) Return(_a0 error) *MockAccountAPI_DisableOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_DisableOTP_Call) RunAndReturn(run func(context.Context, string) error) *MockAccountAPI_DisableOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateOTP provides a mock function with given fields: ctx
func (_m *MockAccountAPI) GenerateOTP(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateOTP")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GenerateOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateOTP'
type MockAccountAPI_GenerateOTP_Call struct {
	*mock.Call
}

// GenerateOTP is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GenerateOTP(ctx interface{}) *MockAccountAPI_GenerateOTP_Call {
	return &MockAccountAPI_GenerateOTP_Call{Call: _e.mock.On("GenerateOTP", ctx)}
}

func (_c *MockAccountAPI_GenerateOTP_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GenerateOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_GenerateOTP_Call) Return(_a0 string, _a1 error) *MockAccountAPI_GenerateOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GenerateOTP_Call) RunAndReturn(run func(context.Context) (string, error)) *MockAccountAPI_GenerateOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx
func (_m *MockAccountAPI) GetAccount(ctx context.Context) (*account.AccountInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *account.AccountInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*account.AccountInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *account.AccountInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.AccountInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockAccountAPI_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetAccount(ctx interface{}) *MockAccountAPI_GetAccount_Call {
	return &MockAccountAPI_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx)}
}

func (_c *MockAccountAPI_GetAccount_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_GetAccount_Call) Return(_a0 *account.AccountInfo, _a1 error) *MockAccountAPI_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetAccount_Call) RunAndReturn(run func(context.Context) (*account.AccountInfo, error)) *MockAccountAPI_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvatar provides a mock function with given fields: ctx
func (_m *MockAccountAPI) GetAvatar(ctx context.Context) ([]byte, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatar")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatar'
type MockAccountAPI_GetAvatar_Call struct {
	*mock.Call
}

// GetAvatar is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetAvatar(ctx interface{}) *MockAccountAPI_GetAvatar_Call {
	return &MockAccountAPI_GetAvatar_Call{Call: _e.mock.On("GetAvatar", ctx)}
}

func (_c *MockAccountAPI_GetAvatar_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_GetAvatar_Call) Return(_a0 []byte, _a1 error) *MockAccountAPI_GetAvatar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetAvatar_Call) RunAndReturn(run func(context.Context) ([]byte, error)) *MockAccountAPI_GetAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function with given fields: ctx
func (_m *MockAccountAPI) GetBalance(ctx context.Context) (*account.Balance, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *account.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*account.Balance, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *account.Balance); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Balance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockAccountAPI_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetBalance(ctx interface{}) *MockAccountAPI_GetBalance_Call {
	return &MockAccountAPI_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx)}
}

func (_c *MockAccountAPI_GetBalance_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_GetBalance_Call) Return(_a0 *account.Balance, _a1 error) *MockAccountAPI_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetBalance_Call) RunAndReturn(run func(context.Context) (*account.Balance, error)) *MockAccountAPI_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetCheckoutSessionStatus provides a mock function with given fields: ctx, sessionID, opts
func (_m *MockAccountAPI) GetCheckoutSessionStatus(ctx context.Context, sessionID string, opts ...account.CheckoutSessionStatusOption) (*account.CheckoutSessionStatus, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, sessionID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckoutSessionStatus")
	}

	var r0 *account.CheckoutSessionStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...account.CheckoutSessionStatusOption) (*account.CheckoutSessionStatus, error)); ok {
		return rf(ctx, sessionID, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...account.CheckoutSessionStatusOption) *account.CheckoutSessionStatus); ok {
		r0 = rf(ctx, sessionID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.CheckoutSessionStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...account.CheckoutSessionStatusOption) error); ok {
		r1 = rf(ctx, sessionID, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetCheckoutSessionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckoutSessionStatus'
type MockAccountAPI_GetCheckoutSessionStatus_Call struct {
	*mock.Call
}

// GetCheckoutSessionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - opts ...account.CheckoutSessionStatusOption
func (_e *MockAccountAPI_Expecter) GetCheckoutSessionStatus(ctx interface{}, sessionID interface{}, opts ...interface{}) *MockAccountAPI_GetCheckoutSessionStatus_Call {
	return &MockAccountAPI_GetCheckoutSessionStatus_Call{Call: _e.mock.On("GetCheckoutSessionStatus",
		append([]interface{}{ctx, sessionID}, opts...)...)}
}

func (_c *MockAccountAPI_GetCheckoutSessionStatus_Call) Run(run func(ctx context.Context, sessionID string, opts ...account.CheckoutSessionStatusOption)) *MockAccountAPI_GetCheckoutSessionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]account.CheckoutSessionStatusOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(account.CheckoutSessionStatusOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAccountAPI_GetCheckoutSessionStatus_Call) Return(_a0 *account.CheckoutSessionStatus, _a1 error) *MockAccountAPI_GetCheckoutSessionStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetCheckoutSessionStatus_Call) RunAndReturn(run func(context.Context, string, ...account.CheckoutSessionStatusOption) (*account.CheckoutSessionStatus, error)) *MockAccountAPI_GetCheckoutSessionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetCheckoutUI provides a mock function with given fields: ctx, planID, opts
func (_m *MockAccountAPI) GetCheckoutUI(ctx context.Context, planID string, opts ...account.CheckoutUIOption) (*account.CheckoutUI, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, planID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckoutUI")
	}

	var r0 *account.CheckoutUI
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...account.CheckoutUIOption) (*account.CheckoutUI, error)); ok {
		return rf(ctx, planID, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...account.CheckoutUIOption) *account.CheckoutUI); ok {
		r0 = rf(ctx, planID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.CheckoutUI)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...account.CheckoutUIOption) error); ok {
		r1 = rf(ctx, planID, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetCheckoutUI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckoutUI'
type MockAccountAPI_GetCheckoutUI_Call struct {
	*mock.Call
}

// GetCheckoutUI is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
//   - opts ...account.CheckoutUIOption
func (_e *MockAccountAPI_Expecter) GetCheckoutUI(ctx interface{}, planID interface{}, opts ...interface{}) *MockAccountAPI_GetCheckoutUI_Call {
	return &MockAccountAPI_GetCheckoutUI_Call{Call: _e.mock.On("GetCheckoutUI",
		append([]interface{}{ctx, planID}, opts...)...)}
}

func (_c *MockAccountAPI_GetCheckoutUI_Call) Run(run func(ctx context.Context, planID string, opts ...account.CheckoutUIOption)) *MockAccountAPI_GetCheckoutUI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]account.CheckoutUIOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(account.CheckoutUIOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockAccountAPI_GetCheckoutUI_Call) Return(_a0 *account.CheckoutUI, _a1 error) *MockAccountAPI_GetCheckoutUI_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetCheckoutUI_Call) RunAndReturn(run func(context.Context, string, ...account.CheckoutUIOption) (*account.CheckoutUI, error)) *MockAccountAPI_GetCheckoutUI_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerPortalURL provides a mock function with given fields: ctx
func (_m *MockAccountAPI) GetCustomerPortalURL(ctx context.Context) (*account.ManagementResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerPortalURL")
	}

	var r0 *account.ManagementResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*account.ManagementResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *account.ManagementResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ManagementResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetCustomerPortalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerPortalURL'
type MockAccountAPI_GetCustomerPortalURL_Call struct {
	*mock.Call
}

// GetCustomerPortalURL is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetCustomerPortalURL(ctx interface{}) *MockAccountAPI_GetCustomerPortalURL_Call {
	return &MockAccountAPI_GetCustomerPortalURL_Call{Call: _e.mock.On("GetCustomerPortalURL", ctx)}
}

func (_c *MockAccountAPI_GetCustomerPortalURL_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetCustomerPortalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_GetCustomerPortalURL_Call) Return(_a0 *account.ManagementResult, _a1 error) *MockAccountAPI_GetCustomerPortalURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetCustomerPortalURL_Call) RunAndReturn(run func(context.Context) (*account.ManagementResult, error)) *MockAccountAPI_GetCustomerPortalURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetGatewayLogo provides a mock function with given fields: ctx, gatewayID
func (_m *MockAccountAPI) GetGatewayLogo(ctx context.Context, gatewayID string) (*account.GatewayLogo, error) {
	ret := _m.Called(ctx, gatewayID)

	if len(ret) == 0 {
		panic("no return value specified for GetGatewayLogo")
	}

	var r0 *account.GatewayLogo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*account.GatewayLogo, error)); ok {
		return rf(ctx, gatewayID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *account.GatewayLogo); ok {
		r0 = rf(ctx, gatewayID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.GatewayLogo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, gatewayID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetGatewayLogo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGatewayLogo'
type MockAccountAPI_GetGatewayLogo_Call struct {
	*mock.Call
}

// GetGatewayLogo is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID string
func (_e *MockAccountAPI_Expecter) GetGatewayLogo(ctx interface{}, gatewayID interface{}) *MockAccountAPI_GetGatewayLogo_Call {
	return &MockAccountAPI_GetGatewayLogo_Call{Call: _e.mock.On("GetGatewayLogo", ctx, gatewayID)}
}

func (_c *MockAccountAPI_GetGatewayLogo_Call) Run(run func(ctx context.Context, gatewayID string)) *MockAccountAPI_GetGatewayLogo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountAPI_GetGatewayLogo_Call) Return(_a0 *account.GatewayLogo, _a1 error) *MockAccountAPI_GetGatewayLogo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetGatewayLogo_Call) RunAndReturn(run func(context.Context, string) (*account.GatewayLogo, error)) *MockAccountAPI_GetGatewayLogo_Call {
	_c.Call.Return(run)
	return _c
}

// GetManagementCapabilities provides a mock function with given fields: ctx
func (_m *MockAccountAPI) GetManagementCapabilities(ctx context.Context) (*account.ManagementCapabilities, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetManagementCapabilities")
	}

	var r0 *account.ManagementCapabilities
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*account.ManagementCapabilities, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *account.ManagementCapabilities); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ManagementCapabilities)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetManagementCapabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManagementCapabilities'
type MockAccountAPI_GetManagementCapabilities_Call struct {
	*mock.Call
}

// GetManagementCapabilities is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetManagementCapabilities(ctx interface{}) *MockAccountAPI_GetManagementCapabilities_Call {
	return &MockAccountAPI_GetManagementCapabilities_Call{Call: _e.mock.On("GetManagementCapabilities", ctx)}
}

func (_c *MockAccountAPI_GetManagementCapabilities_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetManagementCapabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_GetManagementCapabilities_Call) Return(_a0 *account.ManagementCapabilities, _a1 error) *MockAccountAPI_GetManagementCapabilities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetManagementCapabilities_Call) RunAndReturn(run func(context.Context) (*account.ManagementCapabilities, error)) *MockAccountAPI_GetManagementCapabilities_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperation provides a mock function with given fields: ctx, id
func (_m *MockAccountAPI) GetOperation(ctx context.Context, id int64) (*account.Operation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOperation")
	}

	var r0 *account.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*account.Operation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *account.Operation); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperation'
type MockAccountAPI_GetOperation_Call struct {
	*mock.Call
}

// GetOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAccountAPI_Expecter) GetOperation(ctx interface{}, id interface{}) *MockAccountAPI_GetOperation_Call {
	return &MockAccountAPI_GetOperation_Call{Call: _e.mock.On("GetOperation", ctx, id)}
}

func (_c *MockAccountAPI_GetOperation_Call) Run(run func(ctx context.Context, id int64)) *MockAccountAPI_GetOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAccountAPI_GetOperation_Call) Return(_a0 *account.Operation, _a1 error) *MockAccountAPI_GetOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetOperation_Call) RunAndReturn(run func(context.Context, int64) (*account.Operation, error)) *MockAccountAPI_GetOperation_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperationFilters provides a mock function with given fields: ctx
func (_m *MockAccountAPI) GetOperationFilters(ctx context.Context) (*account.OperationFilters, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOperationFilters")
	}

	var r0 *account.OperationFilters
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*account.OperationFilters, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *account.OperationFilters); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.OperationFilters)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetOperationFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperationFilters'
type MockAccountAPI_GetOperationFilters_Call struct {
	*mock.Call
}

// GetOperationFilters is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetOperationFilters(ctx interface{}) *MockAccountAPI_GetOperationFilters_Call {
	return &MockAccountAPI_GetOperationFilters_Call{Call: _e.mock.On("GetOperationFilters", ctx)}
}

func (_c *MockAccountAPI_GetOperationFilters_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetOperationFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_GetOperationFilters_Call) Return(_a0 *account.OperationFilters, _a1 error) *MockAccountAPI_GetOperationFilters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetOperationFilters_Call) RunAndReturn(run func(context.Context) (*account.OperationFilters, error)) *MockAccountAPI_GetOperationFilters_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissions provides a mock function with given fields: ctx
func (_m *MockAccountAPI) GetPermissions(ctx context.Context) (*account.AccountPermissions, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 *account.AccountPermissions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*account.AccountPermissions, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *account.AccountPermissions); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.AccountPermissions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissions'
type MockAccountAPI_GetPermissions_Call struct {
	*mock.Call
}

// GetPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetPermissions(ctx interface{}) *MockAccountAPI_GetPermissions_Call {
	return &MockAccountAPI_GetPermissions_Call{Call: _e.mock.On("GetPermissions", ctx)}
}

func (_c *MockAccountAPI_GetPermissions_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_GetPermissions_Call) Return(_a0 *account.AccountPermissions, _a1 error) *MockAccountAPI_GetPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetPermissions_Call) RunAndReturn(run func(context.Context) (*account.AccountPermissions, error)) *MockAccountAPI_GetPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuota provides a mock function with given fields: ctx
func (_m *MockAccountAPI) GetQuota(ctx context.Context) (*account.QuotaStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetQuota")
	}

	var r0 *account.QuotaStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*account.QuotaStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *account.QuotaStatus); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.QuotaStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetQuota_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuota'
type MockAccountAPI_GetQuota_Call struct {
	*mock.Call
}

// GetQuota is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetQuota(ctx interface{}) *MockAccountAPI_GetQuota_Call {
	return &MockAccountAPI_GetQuota_Call{Call: _e.mock.On("GetQuota", ctx)}
}

func (_c *MockAccountAPI_GetQuota_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetQuota_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_GetQuota_Call) Return(_a0 *account.QuotaStatus, _a1 error) *MockAccountAPI_GetQuota_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetQuota_Call) RunAndReturn(run func(context.Context) (*account.QuotaStatus, error)) *MockAccountAPI_GetQuota_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotaHistory provides a mock function with given fields: ctx, startDate, endDate, usageType
func (_m *MockAccountAPI) GetQuotaHistory(ctx context.Context, startDate string, endDate string, usageType string) (*account.QuotaHistory, error) {
	ret := _m.Called(ctx, startDate, endDate, usageType)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotaHistory")
	}

	var r0 *account.QuotaHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*account.QuotaHistory, error)); ok {
		return rf(ctx, startDate, endDate, usageType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *account.QuotaHistory); ok {
		r0 = rf(ctx, startDate, endDate, usageType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.QuotaHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, startDate, endDate, usageType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetQuotaHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotaHistory'
type MockAccountAPI_GetQuotaHistory_Call struct {
	*mock.Call
}

// GetQuotaHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate string
//   - endDate string
//   - usageType string
func (_e *MockAccountAPI_Expecter) GetQuotaHistory(ctx interface{}, startDate interface{}, endDate interface{}, usageType interface{}) *MockAccountAPI_GetQuotaHistory_Call {
	return &MockAccountAPI_GetQuotaHistory_Call{Call: _e.mock.On("GetQuotaHistory", ctx, startDate, endDate, usageType)}
}

func (_c *MockAccountAPI_GetQuotaHistory_Call) Run(run func(ctx context.Context, startDate string, endDate string, usageType string)) *MockAccountAPI_GetQuotaHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAccountAPI_GetQuotaHistory_Call) Return(_a0 *account.QuotaHistory, _a1 error) *MockAccountAPI_GetQuotaHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetQuotaHistory_Call) RunAndReturn(run func(context.Context, string, string, string) (*account.QuotaHistory, error)) *MockAccountAPI_GetQuotaHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionStatus provides a mock function with given fields: ctx
func (_m *MockAccountAPI) GetSubscriptionStatus(ctx context.Context) (*account.SubscriptionStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionStatus")
	}

	var r0 *account.SubscriptionStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*account.SubscriptionStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *account.SubscriptionStatus); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.SubscriptionStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_GetSubscriptionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionStatus'
type MockAccountAPI_GetSubscriptionStatus_Call struct {
	*mock.Call
}

// GetSubscriptionStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetSubscriptionStatus(ctx interface{}) *MockAccountAPI_GetSubscriptionStatus_Call {
	return &MockAccountAPI_GetSubscriptionStatus_Call{Call: _e.mock.On("GetSubscriptionStatus", ctx)}
}

func (_c *MockAccountAPI_GetSubscriptionStatus_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetSubscriptionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_GetSubscriptionStatus_Call) Return(_a0 *account.SubscriptionStatus, _a1 error) *MockAccountAPI_GetSubscriptionStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_GetSubscriptionStatus_Call) RunAndReturn(run func(context.Context) (*account.SubscriptionStatus, error)) *MockAccountAPI_GetSubscriptionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// HandleWebhook provides a mock function with given fields: ctx, gatewayType, webhookData
func (_m *MockAccountAPI) HandleWebhook(ctx context.Context, gatewayType string, webhookData map[string]interface{}) error {
	ret := _m.Called(ctx, gatewayType, webhookData)

	if len(ret) == 0 {
		panic("no return value specified for HandleWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, gatewayType, webhookData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_HandleWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleWebhook'
type MockAccountAPI_HandleWebhook_Call struct {
	*mock.Call
}

// HandleWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayType string
//   - webhookData map[string]interface{}
func (_e *MockAccountAPI_Expecter) HandleWebhook(ctx interface{}, gatewayType interface{}, webhookData interface{}) *MockAccountAPI_HandleWebhook_Call {
	return &MockAccountAPI_HandleWebhook_Call{Call: _e.mock.On("HandleWebhook", ctx, gatewayType, webhookData)}
}

func (_c *MockAccountAPI_HandleWebhook_Call) Run(run func(ctx context.Context, gatewayType string, webhookData map[string]interface{})) *MockAccountAPI_HandleWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockAccountAPI_HandleWebhook_Call) Return(_a0 error) *MockAccountAPI_HandleWebhook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_HandleWebhook_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) error) *MockAccountAPI_HandleWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// ListAPIKeys provides a mock function with given fields: ctx, opts
func (_m *MockAccountAPI) ListAPIKeys(ctx context.Context, opts ...account.ListOption) ([]*account.APIKey, int, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListAPIKeys")
	}

	var r0 []*account.APIKey
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, ...account.ListOption) ([]*account.APIKey, int, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...account.ListOption) []*account.APIKey); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*account.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...account.ListOption) int); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, ...account.ListOption) error); ok {
		r2 = rf(ctx, opts...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAccountAPI_ListAPIKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAPIKeys'
type MockAccountAPI_ListAPIKeys_Call struct {
	*mock.Call
}

// ListAPIKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...account.ListOption
func (_e *MockAccountAPI_Expecter) ListAPIKeys(ctx interface{}, opts ...interface{}) *MockAccountAPI_ListAPIKeys_Call {
	return &MockAccountAPI_ListAPIKeys_Call{Call: _e.mock.On("ListAPIKeys",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockAccountAPI_ListAPIKeys_Call) Run(run func(ctx context.Context, opts ...account.ListOption)) *MockAccountAPI_ListAPIKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]account.ListOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(account.ListOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockAccountAPI_ListAPIKeys_Call) Return(_a0 []*account.APIKey, _a1 int, _a2 error) *MockAccountAPI_ListAPIKeys_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAccountAPI_ListAPIKeys_Call) RunAndReturn(run func(context.Context, ...account.ListOption) ([]*account.APIKey, int, error)) *MockAccountAPI_ListAPIKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListBillingGateways provides a mock function with given fields: ctx
func (_m *MockAccountAPI) ListBillingGateways(ctx context.Context) ([]*account.Gateway, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBillingGateways")
	}

	var r0 []*account.Gateway
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*account.Gateway, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*account.Gateway); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*account.Gateway)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_ListBillingGateways_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBillingGateways'
type MockAccountAPI_ListBillingGateways_Call struct {
	*mock.Call
}

// ListBillingGateways is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) ListBillingGateways(ctx interface{}) *MockAccountAPI_ListBillingGateways_Call {
	return &MockAccountAPI_ListBillingGateways_Call{Call: _e.mock.On("ListBillingGateways", ctx)}
}

func (_c *MockAccountAPI_ListBillingGateways_Call) Run(run func(ctx context.Context)) *MockAccountAPI_ListBillingGateways_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_ListBillingGateways_Call) Return(_a0 []*account.Gateway, _a1 error) *MockAccountAPI_ListBillingGateways_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_ListBillingGateways_Call) RunAndReturn(run func(context.Context) ([]*account.Gateway, error)) *MockAccountAPI_ListBillingGateways_Call {
	_c.Call.Return(run)
	return _c
}

// ListCredits provides a mock function with given fields: ctx
func (_m *MockAccountAPI) ListCredits(ctx context.Context) ([]*account.Credit, int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCredits")
	}

	var r0 []*account.Credit
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*account.Credit, int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*account.Credit); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*account.Credit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAccountAPI_ListCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCredits'
type MockAccountAPI_ListCredits_Call struct {
	*mock.Call
}

// ListCredits is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) ListCredits(ctx interface{}) *MockAccountAPI_ListCredits_Call {
	return &MockAccountAPI_ListCredits_Call{Call: _e.mock.On("ListCredits", ctx)}
}

func (_c *MockAccountAPI_ListCredits_Call) Run(run func(ctx context.Context)) *MockAccountAPI_ListCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_ListCredits_Call) Return(_a0 []*account.Credit, _a1 int, _a2 error) *MockAccountAPI_ListCredits_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAccountAPI_ListCredits_Call) RunAndReturn(run func(context.Context) ([]*account.Credit, int, error)) *MockAccountAPI_ListCredits_Call {
	_c.Call.Return(run)
	return _c
}

// ListOperations provides a mock function with given fields: ctx, opts
func (_m *MockAccountAPI) ListOperations(ctx context.Context, opts ...account.ListOption) ([]*account.Operation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListOperations")
	}

	var r0 []*account.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...account.ListOption) ([]*account.Operation, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...account.ListOption) []*account.Operation); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*account.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...account.ListOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_ListOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOperations'
type MockAccountAPI_ListOperations_Call struct {
	*mock.Call
}

// ListOperations is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...account.ListOption
func (_e *MockAccountAPI_Expecter) ListOperations(ctx interface{}, opts ...interface{}) *MockAccountAPI_ListOperations_Call {
	return &MockAccountAPI_ListOperations_Call{Call: _e.mock.On("ListOperations",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockAccountAPI_ListOperations_Call) Run(run func(ctx context.Context, opts ...account.ListOption)) *MockAccountAPI_ListOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]account.ListOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(account.ListOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockAccountAPI_ListOperations_Call) Return(_a0 []*account.Operation, _a1 error) *MockAccountAPI_ListOperations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_ListOperations_Call) RunAndReturn(run func(context.Context, ...account.ListOption) ([]*account.Operation, error)) *MockAccountAPI_ListOperations_Call {
	_c.Call.Return(run)
	return _c
}

// ListPricingPlans provides a mock function with given fields: ctx
func (_m *MockAccountAPI) ListPricingPlans(ctx context.Context) ([]*account.PricingPlanPublic, int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPricingPlans")
	}

	var r0 []*account.PricingPlanPublic
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*account.PricingPlanPublic, int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*account.PricingPlanPublic); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*account.PricingPlanPublic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAccountAPI_ListPricingPlans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPricingPlans'
type MockAccountAPI_ListPricingPlans_Call struct {
	*mock.Call
}

// ListPricingPlans is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) ListPricingPlans(ctx interface{}) *MockAccountAPI_ListPricingPlans_Call {
	return &MockAccountAPI_ListPricingPlans_Call{Call: _e.mock.On("ListPricingPlans", ctx)}
}

func (_c *MockAccountAPI_ListPricingPlans_Call) Run(run func(ctx context.Context)) *MockAccountAPI_ListPricingPlans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_ListPricingPlans_Call) Return(_a0 []*account.PricingPlanPublic, _a1 int, _a2 error) *MockAccountAPI_ListPricingPlans_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAccountAPI_ListPricingPlans_Call) RunAndReturn(run func(context.Context) ([]*account.PricingPlanPublic, int, error)) *MockAccountAPI_ListPricingPlans_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *MockAccountAPI) Login(ctx context.Context, email string, password string) (*account.LoginResult, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *account.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*account.LoginResult, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *account.LoginResult); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.LoginResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAccountAPI_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAccountAPI_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockAccountAPI_Login_Call {
	return &MockAccountAPI_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockAccountAPI_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockAccountAPI_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAccountAPI_Login_Call) Return(_a0 *account.LoginResult, _a1 error) *MockAccountAPI_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_Login_Call) RunAndReturn(run func(context.Context, string, string) (*account.LoginResult, error)) *MockAccountAPI_Login_Call {
	_c.Call.Return(run)
	return _c
}

// LoginWithAPIKey provides a mock function with given fields: ctx, apiKey
func (_m *MockAccountAPI) LoginWithAPIKey(ctx context.Context, apiKey string) (string, error) {
	ret := _m.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for LoginWithAPIKey")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, apiKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, apiKey)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_LoginWithAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginWithAPIKey'
type MockAccountAPI_LoginWithAPIKey_Call struct {
	*mock.Call
}

// LoginWithAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey string
func (_e *MockAccountAPI_Expecter) LoginWithAPIKey(ctx interface{}, apiKey interface{}) *MockAccountAPI_LoginWithAPIKey_Call {
	return &MockAccountAPI_LoginWithAPIKey_Call{Call: _e.mock.On("LoginWithAPIKey", ctx, apiKey)}
}

func (_c *MockAccountAPI_LoginWithAPIKey_Call) Run(run func(ctx context.Context, apiKey string)) *MockAccountAPI_LoginWithAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountAPI_LoginWithAPIKey_Call) Return(_a0 string, _a1 error) *MockAccountAPI_LoginWithAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_LoginWithAPIKey_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockAccountAPI_LoginWithAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// ManageBilling provides a mock function with given fields: ctx, request
func (_m *MockAccountAPI) ManageBilling(ctx context.Context, request account.ManagementRequest) (*account.ManagementResult, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ManageBilling")
	}

	var r0 *account.ManagementResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, account.ManagementRequest) (*account.ManagementResult, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, account.ManagementRequest) *account.ManagementResult); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ManagementResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, account.ManagementRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_ManageBilling_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ManageBilling'
type MockAccountAPI_ManageBilling_Call struct {
	*mock.Call
}

// ManageBilling is a helper method to define mock.On call
//   - ctx context.Context
//   - request account.ManagementRequest
func (_e *MockAccountAPI_Expecter) ManageBilling(ctx interface{}, request interface{}) *MockAccountAPI_ManageBilling_Call {
	return &MockAccountAPI_ManageBilling_Call{Call: _e.mock.On("ManageBilling", ctx, request)}
}

func (_c *MockAccountAPI_ManageBilling_Call) Run(run func(ctx context.Context, request account.ManagementRequest)) *MockAccountAPI_ManageBilling_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(account.ManagementRequest))
	})
	return _c
}

func (_c *MockAccountAPI_ManageBilling_Call) Return(_a0 *account.ManagementResult, _a1 error) *MockAccountAPI_ManageBilling_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_ManageBilling_Call) RunAndReturn(run func(context.Context, account.ManagementRequest) (*account.ManagementResult, error)) *MockAccountAPI_ManageBilling_Call {
	_c.Call.Return(run)
	return _c
}

// PauseBilling provides a mock function with given fields: ctx
func (_m *MockAccountAPI) PauseBilling(ctx context.Context) (*account.ManagementResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PauseBilling")
	}

	var r0 *account.ManagementResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*account.ManagementResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *account.ManagementResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ManagementResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_PauseBilling_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseBilling'
type MockAccountAPI_PauseBilling_Call struct {
	*mock.Call
}

// PauseBilling is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) PauseBilling(ctx interface{}) *MockAccountAPI_PauseBilling_Call {
	return &MockAccountAPI_PauseBilling_Call{Call: _e.mock.On("PauseBilling", ctx)}
}

func (_c *MockAccountAPI_PauseBilling_Call) Run(run func(ctx context.Context)) *MockAccountAPI_PauseBilling_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_PauseBilling_Call) Return(_a0 *account.ManagementResult, _a1 error) *MockAccountAPI_PauseBilling_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_PauseBilling_Call) RunAndReturn(run func(context.Context) (*account.ManagementResult, error)) *MockAccountAPI_PauseBilling_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockAccountAPI) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockAccountAPI_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) Ping(ctx interface{}) *MockAccountAPI_Ping_Call {
	return &MockAccountAPI_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockAccountAPI_Ping_Call) Run(run func(ctx context.Context)) *MockAccountAPI_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_Ping_Call) Return(_a0 error) *MockAccountAPI_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_Ping_Call) RunAndReturn(run func(context.Context) error) *MockAccountAPI_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, email, firstName, lastName, password
func (_m *MockAccountAPI) Register(ctx context.Context, email string, firstName string, lastName string, password string) error {
	ret := _m.Called(ctx, email, firstName, lastName, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, email, firstName, lastName, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAccountAPI_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - firstName string
//   - lastName string
//   - password string
func (_e *MockAccountAPI_Expecter) Register(ctx interface{}, email interface{}, firstName interface{}, lastName interface{}, password interface{}) *MockAccountAPI_Register_Call {
	return &MockAccountAPI_Register_Call{Call: _e.mock.On("Register", ctx, email, firstName, lastName, password)}
}

func (_c *MockAccountAPI_Register_Call) Run(run func(ctx context.Context, email string, firstName string, lastName string, password string)) *MockAccountAPI_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAccountAPI_Register_Call) Return(_a0 error) *MockAccountAPI_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_Register_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *MockAccountAPI_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPasswordReset provides a mock function with given fields: ctx, email
func (_m *MockAccountAPI) RequestPasswordReset(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_RequestPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPasswordReset'
type MockAccountAPI_RequestPasswordReset_Call struct {
	*mock.Call
}

// RequestPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAccountAPI_Expecter) RequestPasswordReset(ctx interface{}, email interface{}) *MockAccountAPI_RequestPasswordReset_Call {
	return &MockAccountAPI_RequestPasswordReset_Call{Call: _e.mock.On("RequestPasswordReset", ctx, email)}
}

func (_c *MockAccountAPI_RequestPasswordReset_Call) Run(run func(ctx context.Context, email string)) *MockAccountAPI_RequestPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountAPI_RequestPasswordReset_Call) Return(_a0 error) *MockAccountAPI_RequestPasswordReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_RequestPasswordReset_Call) RunAndReturn(run func(context.Context, string) error) *MockAccountAPI_RequestPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// ResendVerifyEmail provides a mock function with given fields: ctx, email
func (_m *MockAccountAPI) ResendVerifyEmail(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ResendVerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_ResendVerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendVerifyEmail'
type MockAccountAPI_ResendVerifyEmail_Call struct {
	*mock.Call
}

// ResendVerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAccountAPI_Expecter) ResendVerifyEmail(ctx interface{}, email interface{}) *MockAccountAPI_ResendVerifyEmail_Call {
	return &MockAccountAPI_ResendVerifyEmail_Call{Call: _e.mock.On("ResendVerifyEmail", ctx, email)}
}

func (_c *MockAccountAPI_ResendVerifyEmail_Call) Run(run func(ctx context.Context, email string)) *MockAccountAPI_ResendVerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountAPI_ResendVerifyEmail_Call) Return(_a0 error) *MockAccountAPI_ResendVerifyEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_ResendVerifyEmail_Call) RunAndReturn(run func(context.Context, string) error) *MockAccountAPI_ResendVerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ResumeBilling provides a mock function with given fields: ctx
func (_m *MockAccountAPI) ResumeBilling(ctx context.Context) (*account.ManagementResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResumeBilling")
	}

	var r0 *account.ManagementResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*account.ManagementResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *account.ManagementResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ManagementResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_ResumeBilling_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumeBilling'
type MockAccountAPI_ResumeBilling_Call struct {
	*mock.Call
}

// ResumeBilling is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) ResumeBilling(ctx interface{}) *MockAccountAPI_ResumeBilling_Call {
	return &MockAccountAPI_ResumeBilling_Call{Call: _e.mock.On("ResumeBilling", ctx)}
}

func (_c *MockAccountAPI_ResumeBilling_Call) Run(run func(ctx context.Context)) *MockAccountAPI_ResumeBilling_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_ResumeBilling_Call) Return(_a0 *account.ManagementResult, _a1 error) *MockAccountAPI_ResumeBilling_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_ResumeBilling_Call) RunAndReturn(run func(context.Context) (*account.ManagementResult, error)) *MockAccountAPI_ResumeBilling_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeBillingEvents provides a mock function with given fields: ctx, opts
func (_m *MockAccountAPI) SubscribeBillingEvents(ctx context.Context, opts ...account.SSEOption) (*account.SubscriptionEventStream, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeBillingEvents")
	}

	var r0 *account.SubscriptionEventStream
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...account.SSEOption) (*account.SubscriptionEventStream, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...account.SSEOption) *account.SubscriptionEventStream); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.SubscriptionEventStream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...account.SSEOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_SubscribeBillingEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeBillingEvents'
type MockAccountAPI_SubscribeBillingEvents_Call struct {
	*mock.Call
}

// SubscribeBillingEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...account.SSEOption
func (_e *MockAccountAPI_Expecter) SubscribeBillingEvents(ctx interface{}, opts ...interface{}) *MockAccountAPI_SubscribeBillingEvents_Call {
	return &MockAccountAPI_SubscribeBillingEvents_Call{Call: _e.mock.On("SubscribeBillingEvents",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockAccountAPI_SubscribeBillingEvents_Call) Run(run func(ctx context.Context, opts ...account.SSEOption)) *MockAccountAPI_SubscribeBillingEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]account.SSEOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(account.SSEOption)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockAccountAPI_SubscribeBillingEvents_Call) Return(_a0 *account.SubscriptionEventStream, _a1 error) *MockAccountAPI_SubscribeBillingEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_SubscribeBillingEvents_Call) RunAndReturn(run func(context.Context, ...account.SSEOption) (*account.SubscriptionEventStream, error)) *MockAccountAPI_SubscribeBillingEvents_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEmail provides a mock function with given fields: ctx, email, password
func (_m *MockAccountAPI) UpdateEmail(ctx context.Context, email string, password string) error {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_UpdateEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEmail'
type MockAccountAPI_UpdateEmail_Call struct {
	*mock.Call
}

// UpdateEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAccountAPI_Expecter) UpdateEmail(ctx interface{}, email interface{}, password interface{}) *MockAccountAPI_UpdateEmail_Call {
	return &MockAccountAPI_UpdateEmail_Call{Call: _e.mock.On("UpdateEmail", ctx, email, password)}
}

func (_c *MockAccountAPI_UpdateEmail_Call) Run(run func(ctx context.Context, email string, password string)) *MockAccountAPI_UpdateEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAccountAPI_UpdateEmail_Call) Return(_a0 error) *MockAccountAPI_UpdateEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_UpdateEmail_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAccountAPI_UpdateEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, currentPassword, newPassword
func (_m *MockAccountAPI) UpdatePassword(ctx context.Context, currentPassword string, newPassword string) error {
	ret := _m.Called(ctx, currentPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, currentPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockAccountAPI_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - currentPassword string
//   - newPassword string
func (_e *MockAccountAPI_Expecter) UpdatePassword(ctx interface{}, currentPassword interface{}, newPassword interface{}) *MockAccountAPI_UpdatePassword_Call {
	return &MockAccountAPI_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, currentPassword, newPassword)}
}

func (_c *MockAccountAPI_UpdatePassword_Call) Run(run func(ctx context.Context, currentPassword string, newPassword string)) *MockAccountAPI_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAccountAPI_UpdatePassword_Call) Return(_a0 error) *MockAccountAPI_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_UpdatePassword_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAccountAPI_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, firstName, lastName
func (_m *MockAccountAPI) UpdateProfile(ctx context.Context, firstName string, lastName string) error {
	ret := _m.Called(ctx, firstName, lastName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, firstName, lastName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockAccountAPI_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - firstName string
//   - lastName string
func (_e *MockAccountAPI_Expecter) UpdateProfile(ctx interface{}, firstName interface{}, lastName interface{}) *MockAccountAPI_UpdateProfile_Call {
	return &MockAccountAPI_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, firstName, lastName)}
}

func (_c *MockAccountAPI_UpdateProfile_Call) Run(run func(ctx context.Context, firstName string, lastName string)) *MockAccountAPI_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAccountAPI_UpdateProfile_Call) Return(_a0 error) *MockAccountAPI_UpdateProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_UpdateProfile_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAccountAPI_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UploadAvatar provides a mock function with given fields: ctx, file
func (_m *MockAccountAPI) UploadAvatar(ctx context.Context, file []byte) error {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_UploadAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAvatar'
type MockAccountAPI_UploadAvatar_Call struct {
	*mock.Call
}

// UploadAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - file []byte
func (_e *MockAccountAPI_Expecter) UploadAvatar(ctx interface{}, file interface{}) *MockAccountAPI_UploadAvatar_Call {
	return &MockAccountAPI_UploadAvatar_Call{Call: _e.mock.On("UploadAvatar", ctx, file)}
}

func (_c *MockAccountAPI_UploadAvatar_Call) Run(run func(ctx context.Context, file []byte)) *MockAccountAPI_UploadAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockAccountAPI_UploadAvatar_Call) Return(_a0 error) *MockAccountAPI_UploadAvatar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_UploadAvatar_Call) RunAndReturn(run func(context.Context, []byte) error) *MockAccountAPI_UploadAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// UploadLimit provides a mock function with given fields: ctx
func (_m *MockAccountAPI) UploadLimit(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UploadLimit")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_UploadLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadLimit'
type MockAccountAPI_UploadLimit_Call struct {
	*mock.Call
}

// UploadLimit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) UploadLimit(ctx interface{}) *MockAccountAPI_UploadLimit_Call {
	return &MockAccountAPI_UploadLimit_Call{Call: _e.mock.On("UploadLimit", ctx)}
}

func (_c *MockAccountAPI_UploadLimit_Call) Run(run func(ctx context.Context)) *MockAccountAPI_UploadLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountAPI_UploadLimit_Call) Return(_a0 int64, _a1 error) *MockAccountAPI_UploadLimit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_UploadLimit_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockAccountAPI_UploadLimit_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateOTP provides a mock function with given fields: ctx, intermediateJWT, otp
func (_m *MockAccountAPI) ValidateOTP(ctx context.Context, intermediateJWT string, otp string) (string, error) {
	ret := _m.Called(ctx, intermediateJWT, otp)

	if len(ret) == 0 {
		panic("no return value specified for ValidateOTP")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, intermediateJWT, otp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, intermediateJWT, otp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, intermediateJWT, otp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_ValidateOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateOTP'
type MockAccountAPI_ValidateOTP_Call struct {
	*mock.Call
}

// ValidateOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - intermediateJWT string
//   - otp string
func (_e *MockAccountAPI_Expecter) ValidateOTP(ctx interface{}, intermediateJWT interface{}, otp interface{}) *MockAccountAPI_ValidateOTP_Call {
	return &MockAccountAPI_ValidateOTP_Call{Call: _e.mock.On("ValidateOTP", ctx, intermediateJWT, otp)}
}

func (_c *MockAccountAPI_ValidateOTP_Call) Run(run func(ctx context.Context, intermediateJWT string, otp string)) *MockAccountAPI_ValidateOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAccountAPI_ValidateOTP_Call) Return(_a0 string, _a1 error) *MockAccountAPI_ValidateOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_ValidateOTP_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockAccountAPI_ValidateOTP_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function with given fields: ctx, email, token
func (_m *MockAccountAPI) VerifyEmail(ctx context.Context, email string, token string) error {
	ret := _m.Called(ctx, email, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type MockAccountAPI_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - token string
func (_e *MockAccountAPI_Expecter) VerifyEmail(ctx interface{}, email interface{}, token interface{}) *MockAccountAPI_VerifyEmail_Call {
	return &MockAccountAPI_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, email, token)}
}

func (_c *MockAccountAPI_VerifyEmail_Call) Run(run func(ctx context.Context, email string, token string)) *MockAccountAPI_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAccountAPI_VerifyEmail_Call) Return(_a0 error) *MockAccountAPI_VerifyEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_VerifyEmail_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAccountAPI_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOTP provides a mock function with given fields: ctx, otp
func (_m *MockAccountAPI) VerifyOTP(ctx context.Context, otp string) error {
	ret := _m.Called(ctx, otp)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountAPI_VerifyOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOTP'
type MockAccountAPI_VerifyOTP_Call struct {
	*mock.Call
}

// VerifyOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - otp string
func (_e *MockAccountAPI_Expecter) VerifyOTP(ctx interface{}, otp interface{}) *MockAccountAPI_VerifyOTP_Call {
	return &MockAccountAPI_VerifyOTP_Call{Call: _e.mock.On("VerifyOTP", ctx, otp)}
}

func (_c *MockAccountAPI_VerifyOTP_Call) Run(run func(ctx context.Context, otp string)) *MockAccountAPI_VerifyOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountAPI_VerifyOTP_Call) Return(_a0 error) *MockAccountAPI_VerifyOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountAPI_VerifyOTP_Call) RunAndReturn(run func(context.Context, string) error) *MockAccountAPI_VerifyOTP_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForOperation provides a mock function with given fields: ctx, id, opts
func (_m *MockAccountAPI) WaitForOperation(ctx context.Context, id int64, opts ...account.PollOption) (*account.Operation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WaitForOperation")
	}

	var r0 *account.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...account.PollOption) (*account.Operation, error)); ok {
		return rf(ctx, id, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...account.PollOption) *account.Operation); ok {
		r0 = rf(ctx, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...account.PollOption) error); ok {
		r1 = rf(ctx, id, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountAPI_WaitForOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForOperation'
type MockAccountAPI_WaitForOperation_Call struct {
	*mock.Call
}

// WaitForOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - opts ...account.PollOption
func (_e *MockAccountAPI_Expecter) WaitForOperation(ctx interface{}, id interface{}, opts ...interface{}) *MockAccountAPI_WaitForOperation_Call {
	return &MockAccountAPI_WaitForOperation_Call{Call: _e.mock.On("WaitForOperation",
		append([]interface{}{ctx, id}, opts...)...)}
}

func (_c *MockAccountAPI_WaitForOperation_Call) Run(run func(ctx context.Context, id int64, opts ...account.PollOption)) *MockAccountAPI_WaitForOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]account.PollOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(account.PollOption)
			}
		}
		run(args[0].(context.Context), args[1].(int64), variadicArgs...)
	})
	return _c
}

func (_c *MockAccountAPI_WaitForOperation_Call) Return(_a0 *account.Operation, _a1 error) *MockAccountAPI_WaitForOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountAPI_WaitForOperation_Call) RunAndReturn(run func(context.Context, int64, ...account.PollOption) (*account.Operation, error)) *MockAccountAPI_WaitForOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountAPI creates a new instance of MockAccountAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountAPI {
	mock := &MockAccountAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
