// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-sdk"
)

// NewMockAccountAPI creates a new instance of MockAccountAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountAPI {
	mock := &MockAccountAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountAPI is an autogenerated mock type for the AccountAPI type
type MockAccountAPI struct {
	mock.Mock
}

type MockAccountAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountAPI) EXPECT() *MockAccountAPI_Expecter {
	return &MockAccountAPI_Expecter{mock: &_m.Mock}
}

// ConfirmPasswordReset provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) ConfirmPasswordReset(ctx context.Context, email string, token string, newPassword string) error {
	ret := _mock.Called(ctx, email, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmPasswordReset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, email, token, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_ConfirmPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmPasswordReset'
type MockAccountAPI_ConfirmPasswordReset_Call struct {
	*mock.Call
}

// ConfirmPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - token string
//   - newPassword string
func (_e *MockAccountAPI_Expecter) ConfirmPasswordReset(ctx interface{}, email interface{}, token interface{}, newPassword interface{}) *MockAccountAPI_ConfirmPasswordReset_Call {
	return &MockAccountAPI_ConfirmPasswordReset_Call{Call: _e.mock.On("ConfirmPasswordReset", ctx, email, token, newPassword)}
}

func (_c *MockAccountAPI_ConfirmPasswordReset_Call) Run(run func(ctx context.Context, email string, token string, newPassword string)) *MockAccountAPI_ConfirmPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAccountAPI_ConfirmPasswordReset_Call) Return(err error) *MockAccountAPI_ConfirmPasswordReset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_ConfirmPasswordReset_Call) RunAndReturn(run func(ctx context.Context, email string, token string, newPassword string) error) *MockAccountAPI_ConfirmPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAPIKey provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) CreateAPIKey(ctx context.Context, name string) (*account.APIKey, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateAPIKey")
	}

	var r0 *account.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*account.APIKey, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *account.APIKey); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_CreateAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAPIKey'
type MockAccountAPI_CreateAPIKey_Call struct {
	*mock.Call
}

// CreateAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAccountAPI_Expecter) CreateAPIKey(ctx interface{}, name interface{}) *MockAccountAPI_CreateAPIKey_Call {
	return &MockAccountAPI_CreateAPIKey_Call{Call: _e.mock.On("CreateAPIKey", ctx, name)}
}

func (_c *MockAccountAPI_CreateAPIKey_Call) Run(run func(ctx context.Context, name string)) *MockAccountAPI_CreateAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountAPI_CreateAPIKey_Call) Return(aPIKey *account.APIKey, err error) *MockAccountAPI_CreateAPIKey_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAccountAPI_CreateAPIKey_Call) RunAndReturn(run func(ctx context.Context, name string) (*account.APIKey, error)) *MockAccountAPI_CreateAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAPIKey provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) DeleteAPIKey(ctx context.Context, keyID string) error {
	ret := _mock.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAPIKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, keyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_DeleteAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAPIKey'
type MockAccountAPI_DeleteAPIKey_Call struct {
	*mock.Call
}

// DeleteAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
func (_e *MockAccountAPI_Expecter) DeleteAPIKey(ctx interface{}, keyID interface{}) *MockAccountAPI_DeleteAPIKey_Call {
	return &MockAccountAPI_DeleteAPIKey_Call{Call: _e.mock.On("DeleteAPIKey", ctx, keyID)}
}

func (_c *MockAccountAPI_DeleteAPIKey_Call) Run(run func(ctx context.Context, keyID string)) *MockAccountAPI_DeleteAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountAPI_DeleteAPIKey_Call) Return(err error) *MockAccountAPI_DeleteAPIKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_DeleteAPIKey_Call) RunAndReturn(run func(ctx context.Context, keyID string) error) *MockAccountAPI_DeleteAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) DeleteAccount(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockAccountAPI_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) DeleteAccount(ctx interface{}) *MockAccountAPI_DeleteAccount_Call {
	return &MockAccountAPI_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx)}
}

func (_c *MockAccountAPI_DeleteAccount_Call) Run(run func(ctx context.Context)) *MockAccountAPI_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountAPI_DeleteAccount_Call) Return(err error) *MockAccountAPI_DeleteAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_DeleteAccount_Call) RunAndReturn(run func(ctx context.Context) error) *MockAccountAPI_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DisableOTP provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) DisableOTP(ctx context.Context, password string) error {
	ret := _mock.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for DisableOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_DisableOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableOTP'
type MockAccountAPI_DisableOTP_Call struct {
	*mock.Call
}

// DisableOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
func (_e *MockAccountAPI_Expecter) DisableOTP(ctx interface{}, password interface{}) *MockAccountAPI_DisableOTP_Call {
	return &MockAccountAPI_DisableOTP_Call{Call: _e.mock.On("DisableOTP", ctx, password)}
}

func (_c *MockAccountAPI_DisableOTP_Call) Run(run func(ctx context.Context, password string)) *MockAccountAPI_DisableOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountAPI_DisableOTP_Call) Return(err error) *MockAccountAPI_DisableOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_DisableOTP_Call) RunAndReturn(run func(ctx context.Context, password string) error) *MockAccountAPI_DisableOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateOTP provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) GenerateOTP(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateOTP")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_GenerateOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateOTP'
type MockAccountAPI_GenerateOTP_Call struct {
	*mock.Call
}

// GenerateOTP is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GenerateOTP(ctx interface{}) *MockAccountAPI_GenerateOTP_Call {
	return &MockAccountAPI_GenerateOTP_Call{Call: _e.mock.On("GenerateOTP", ctx)}
}

func (_c *MockAccountAPI_GenerateOTP_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GenerateOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountAPI_GenerateOTP_Call) Return(s string, err error) *MockAccountAPI_GenerateOTP_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAccountAPI_GenerateOTP_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockAccountAPI_GenerateOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) GetAccount(ctx context.Context) (*account.AccountInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *account.AccountInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*account.AccountInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *account.AccountInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.AccountInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockAccountAPI_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetAccount(ctx interface{}) *MockAccountAPI_GetAccount_Call {
	return &MockAccountAPI_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx)}
}

func (_c *MockAccountAPI_GetAccount_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountAPI_GetAccount_Call) Return(accountInfo *account.AccountInfo, err error) *MockAccountAPI_GetAccount_Call {
	_c.Call.Return(accountInfo, err)
	return _c
}

func (_c *MockAccountAPI_GetAccount_Call) RunAndReturn(run func(ctx context.Context) (*account.AccountInfo, error)) *MockAccountAPI_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvatar provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) GetAvatar(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatar")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_GetAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvatar'
type MockAccountAPI_GetAvatar_Call struct {
	*mock.Call
}

// GetAvatar is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetAvatar(ctx interface{}) *MockAccountAPI_GetAvatar_Call {
	return &MockAccountAPI_GetAvatar_Call{Call: _e.mock.On("GetAvatar", ctx)}
}

func (_c *MockAccountAPI_GetAvatar_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountAPI_GetAvatar_Call) Return(bytes []byte, err error) *MockAccountAPI_GetAvatar_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockAccountAPI_GetAvatar_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockAccountAPI_GetAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperation provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) GetOperation(ctx context.Context, id int64) (*account.Operation, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOperation")
	}

	var r0 *account.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*account.Operation, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *account.Operation); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_GetOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperation'
type MockAccountAPI_GetOperation_Call struct {
	*mock.Call
}

// GetOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAccountAPI_Expecter) GetOperation(ctx interface{}, id interface{}) *MockAccountAPI_GetOperation_Call {
	return &MockAccountAPI_GetOperation_Call{Call: _e.mock.On("GetOperation", ctx, id)}
}

func (_c *MockAccountAPI_GetOperation_Call) Run(run func(ctx context.Context, id int64)) *MockAccountAPI_GetOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountAPI_GetOperation_Call) Return(operation *account.Operation, err error) *MockAccountAPI_GetOperation_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *MockAccountAPI_GetOperation_Call) RunAndReturn(run func(ctx context.Context, id int64) (*account.Operation, error)) *MockAccountAPI_GetOperation_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperationFilters provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) GetOperationFilters(ctx context.Context) (*account.OperationFilters, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOperationFilters")
	}

	var r0 *account.OperationFilters
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*account.OperationFilters, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *account.OperationFilters); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.OperationFilters)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_GetOperationFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperationFilters'
type MockAccountAPI_GetOperationFilters_Call struct {
	*mock.Call
}

// GetOperationFilters is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetOperationFilters(ctx interface{}) *MockAccountAPI_GetOperationFilters_Call {
	return &MockAccountAPI_GetOperationFilters_Call{Call: _e.mock.On("GetOperationFilters", ctx)}
}

func (_c *MockAccountAPI_GetOperationFilters_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetOperationFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountAPI_GetOperationFilters_Call) Return(operationFilters *account.OperationFilters, err error) *MockAccountAPI_GetOperationFilters_Call {
	_c.Call.Return(operationFilters, err)
	return _c
}

func (_c *MockAccountAPI_GetOperationFilters_Call) RunAndReturn(run func(ctx context.Context) (*account.OperationFilters, error)) *MockAccountAPI_GetOperationFilters_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissions provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) GetPermissions(ctx context.Context) (*account.AccountPermissions, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 *account.AccountPermissions
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*account.AccountPermissions, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *account.AccountPermissions); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.AccountPermissions)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_GetPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissions'
type MockAccountAPI_GetPermissions_Call struct {
	*mock.Call
}

// GetPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) GetPermissions(ctx interface{}) *MockAccountAPI_GetPermissions_Call {
	return &MockAccountAPI_GetPermissions_Call{Call: _e.mock.On("GetPermissions", ctx)}
}

func (_c *MockAccountAPI_GetPermissions_Call) Run(run func(ctx context.Context)) *MockAccountAPI_GetPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountAPI_GetPermissions_Call) Return(accountPermissions *account.AccountPermissions, err error) *MockAccountAPI_GetPermissions_Call {
	_c.Call.Return(accountPermissions, err)
	return _c
}

func (_c *MockAccountAPI_GetPermissions_Call) RunAndReturn(run func(ctx context.Context) (*account.AccountPermissions, error)) *MockAccountAPI_GetPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListAPIKeys provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) ListAPIKeys(ctx context.Context, opts ...account.ListOption) ([]*account.APIKey, error) {
	// account.ListOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListAPIKeys")
	}

	var r0 []*account.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...account.ListOption) ([]*account.APIKey, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...account.ListOption) []*account.APIKey); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*account.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...account.ListOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_ListAPIKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAPIKeys'
type MockAccountAPI_ListAPIKeys_Call struct {
	*mock.Call
}

// ListAPIKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...account.ListOption
func (_e *MockAccountAPI_Expecter) ListAPIKeys(ctx interface{}, opts ...interface{}) *MockAccountAPI_ListAPIKeys_Call {
	return &MockAccountAPI_ListAPIKeys_Call{Call: _e.mock.On("ListAPIKeys",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockAccountAPI_ListAPIKeys_Call) Run(run func(ctx context.Context, opts ...account.ListOption)) *MockAccountAPI_ListAPIKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []account.ListOption
		variadicArgs := make([]account.ListOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(account.ListOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAccountAPI_ListAPIKeys_Call) Return(aPIKeys []*account.APIKey, err error) *MockAccountAPI_ListAPIKeys_Call {
	_c.Call.Return(aPIKeys, err)
	return _c
}

func (_c *MockAccountAPI_ListAPIKeys_Call) RunAndReturn(run func(ctx context.Context, opts ...account.ListOption) ([]*account.APIKey, error)) *MockAccountAPI_ListAPIKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListOperations provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) ListOperations(ctx context.Context, opts ...account.ListOption) ([]*account.Operation, error) {
	// account.ListOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListOperations")
	}

	var r0 []*account.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...account.ListOption) ([]*account.Operation, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...account.ListOption) []*account.Operation); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*account.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...account.ListOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_ListOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOperations'
type MockAccountAPI_ListOperations_Call struct {
	*mock.Call
}

// ListOperations is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...account.ListOption
func (_e *MockAccountAPI_Expecter) ListOperations(ctx interface{}, opts ...interface{}) *MockAccountAPI_ListOperations_Call {
	return &MockAccountAPI_ListOperations_Call{Call: _e.mock.On("ListOperations",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockAccountAPI_ListOperations_Call) Run(run func(ctx context.Context, opts ...account.ListOption)) *MockAccountAPI_ListOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []account.ListOption
		variadicArgs := make([]account.ListOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(account.ListOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAccountAPI_ListOperations_Call) Return(operations []*account.Operation, err error) *MockAccountAPI_ListOperations_Call {
	_c.Call.Return(operations, err)
	return _c
}

func (_c *MockAccountAPI_ListOperations_Call) RunAndReturn(run func(ctx context.Context, opts ...account.ListOption) ([]*account.Operation, error)) *MockAccountAPI_ListOperations_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) Login(ctx context.Context, email string, password string) (*account.LoginResult, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *account.LoginResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*account.LoginResult, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *account.LoginResult); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.LoginResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAccountAPI_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAccountAPI_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockAccountAPI_Login_Call {
	return &MockAccountAPI_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockAccountAPI_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockAccountAPI_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountAPI_Login_Call) Return(loginResult *account.LoginResult, err error) *MockAccountAPI_Login_Call {
	_c.Call.Return(loginResult, err)
	return _c
}

func (_c *MockAccountAPI_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*account.LoginResult, error)) *MockAccountAPI_Login_Call {
	_c.Call.Return(run)
	return _c
}

// LoginWithAPIKey provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) LoginWithAPIKey(ctx context.Context, apiKey string) (string, error) {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for LoginWithAPIKey")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_LoginWithAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginWithAPIKey'
type MockAccountAPI_LoginWithAPIKey_Call struct {
	*mock.Call
}

// LoginWithAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey string
func (_e *MockAccountAPI_Expecter) LoginWithAPIKey(ctx interface{}, apiKey interface{}) *MockAccountAPI_LoginWithAPIKey_Call {
	return &MockAccountAPI_LoginWithAPIKey_Call{Call: _e.mock.On("LoginWithAPIKey", ctx, apiKey)}
}

func (_c *MockAccountAPI_LoginWithAPIKey_Call) Run(run func(ctx context.Context, apiKey string)) *MockAccountAPI_LoginWithAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountAPI_LoginWithAPIKey_Call) Return(s string, err error) *MockAccountAPI_LoginWithAPIKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAccountAPI_LoginWithAPIKey_Call) RunAndReturn(run func(ctx context.Context, apiKey string) (string, error)) *MockAccountAPI_LoginWithAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockAccountAPI_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) Ping(ctx interface{}) *MockAccountAPI_Ping_Call {
	return &MockAccountAPI_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockAccountAPI_Ping_Call) Run(run func(ctx context.Context)) *MockAccountAPI_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountAPI_Ping_Call) Return(err error) *MockAccountAPI_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockAccountAPI_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) Register(ctx context.Context, email string, firstName string, lastName string, password string) error {
	ret := _mock.Called(ctx, email, firstName, lastName, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, email, firstName, lastName, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAccountAPI_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - firstName string
//   - lastName string
//   - password string
func (_e *MockAccountAPI_Expecter) Register(ctx interface{}, email interface{}, firstName interface{}, lastName interface{}, password interface{}) *MockAccountAPI_Register_Call {
	return &MockAccountAPI_Register_Call{Call: _e.mock.On("Register", ctx, email, firstName, lastName, password)}
}

func (_c *MockAccountAPI_Register_Call) Run(run func(ctx context.Context, email string, firstName string, lastName string, password string)) *MockAccountAPI_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAccountAPI_Register_Call) Return(err error) *MockAccountAPI_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_Register_Call) RunAndReturn(run func(ctx context.Context, email string, firstName string, lastName string, password string) error) *MockAccountAPI_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPasswordReset provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) RequestPasswordReset(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_RequestPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPasswordReset'
type MockAccountAPI_RequestPasswordReset_Call struct {
	*mock.Call
}

// RequestPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAccountAPI_Expecter) RequestPasswordReset(ctx interface{}, email interface{}) *MockAccountAPI_RequestPasswordReset_Call {
	return &MockAccountAPI_RequestPasswordReset_Call{Call: _e.mock.On("RequestPasswordReset", ctx, email)}
}

func (_c *MockAccountAPI_RequestPasswordReset_Call) Run(run func(ctx context.Context, email string)) *MockAccountAPI_RequestPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountAPI_RequestPasswordReset_Call) Return(err error) *MockAccountAPI_RequestPasswordReset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_RequestPasswordReset_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockAccountAPI_RequestPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// ResendVerifyEmail provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) ResendVerifyEmail(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ResendVerifyEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_ResendVerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendVerifyEmail'
type MockAccountAPI_ResendVerifyEmail_Call struct {
	*mock.Call
}

// ResendVerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAccountAPI_Expecter) ResendVerifyEmail(ctx interface{}, email interface{}) *MockAccountAPI_ResendVerifyEmail_Call {
	return &MockAccountAPI_ResendVerifyEmail_Call{Call: _e.mock.On("ResendVerifyEmail", ctx, email)}
}

func (_c *MockAccountAPI_ResendVerifyEmail_Call) Run(run func(ctx context.Context, email string)) *MockAccountAPI_ResendVerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountAPI_ResendVerifyEmail_Call) Return(err error) *MockAccountAPI_ResendVerifyEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_ResendVerifyEmail_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockAccountAPI_ResendVerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEmail provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) UpdateEmail(ctx context.Context, email string, password string) error {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_UpdateEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEmail'
type MockAccountAPI_UpdateEmail_Call struct {
	*mock.Call
}

// UpdateEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAccountAPI_Expecter) UpdateEmail(ctx interface{}, email interface{}, password interface{}) *MockAccountAPI_UpdateEmail_Call {
	return &MockAccountAPI_UpdateEmail_Call{Call: _e.mock.On("UpdateEmail", ctx, email, password)}
}

func (_c *MockAccountAPI_UpdateEmail_Call) Run(run func(ctx context.Context, email string, password string)) *MockAccountAPI_UpdateEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountAPI_UpdateEmail_Call) Return(err error) *MockAccountAPI_UpdateEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_UpdateEmail_Call) RunAndReturn(run func(ctx context.Context, email string, password string) error) *MockAccountAPI_UpdateEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) UpdatePassword(ctx context.Context, currentPassword string, newPassword string) error {
	ret := _mock.Called(ctx, currentPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, currentPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockAccountAPI_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - currentPassword string
//   - newPassword string
func (_e *MockAccountAPI_Expecter) UpdatePassword(ctx interface{}, currentPassword interface{}, newPassword interface{}) *MockAccountAPI_UpdatePassword_Call {
	return &MockAccountAPI_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, currentPassword, newPassword)}
}

func (_c *MockAccountAPI_UpdatePassword_Call) Run(run func(ctx context.Context, currentPassword string, newPassword string)) *MockAccountAPI_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountAPI_UpdatePassword_Call) Return(err error) *MockAccountAPI_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, currentPassword string, newPassword string) error) *MockAccountAPI_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) UpdateProfile(ctx context.Context, firstName string, lastName string) error {
	ret := _mock.Called(ctx, firstName, lastName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, firstName, lastName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockAccountAPI_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - firstName string
//   - lastName string
func (_e *MockAccountAPI_Expecter) UpdateProfile(ctx interface{}, firstName interface{}, lastName interface{}) *MockAccountAPI_UpdateProfile_Call {
	return &MockAccountAPI_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, firstName, lastName)}
}

func (_c *MockAccountAPI_UpdateProfile_Call) Run(run func(ctx context.Context, firstName string, lastName string)) *MockAccountAPI_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountAPI_UpdateProfile_Call) Return(err error) *MockAccountAPI_UpdateProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, firstName string, lastName string) error) *MockAccountAPI_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UploadAvatar provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) UploadAvatar(ctx context.Context, file []byte) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadAvatar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_UploadAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAvatar'
type MockAccountAPI_UploadAvatar_Call struct {
	*mock.Call
}

// UploadAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - file []byte
func (_e *MockAccountAPI_Expecter) UploadAvatar(ctx interface{}, file interface{}) *MockAccountAPI_UploadAvatar_Call {
	return &MockAccountAPI_UploadAvatar_Call{Call: _e.mock.On("UploadAvatar", ctx, file)}
}

func (_c *MockAccountAPI_UploadAvatar_Call) Run(run func(ctx context.Context, file []byte)) *MockAccountAPI_UploadAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountAPI_UploadAvatar_Call) Return(err error) *MockAccountAPI_UploadAvatar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_UploadAvatar_Call) RunAndReturn(run func(ctx context.Context, file []byte) error) *MockAccountAPI_UploadAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// UploadLimit provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) UploadLimit(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UploadLimit")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_UploadLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadLimit'
type MockAccountAPI_UploadLimit_Call struct {
	*mock.Call
}

// UploadLimit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountAPI_Expecter) UploadLimit(ctx interface{}) *MockAccountAPI_UploadLimit_Call {
	return &MockAccountAPI_UploadLimit_Call{Call: _e.mock.On("UploadLimit", ctx)}
}

func (_c *MockAccountAPI_UploadLimit_Call) Run(run func(ctx context.Context)) *MockAccountAPI_UploadLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountAPI_UploadLimit_Call) Return(n int64, err error) *MockAccountAPI_UploadLimit_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAccountAPI_UploadLimit_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockAccountAPI_UploadLimit_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateOTP provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) ValidateOTP(ctx context.Context, intermediateJWT string, otp string) (string, error) {
	ret := _mock.Called(ctx, intermediateJWT, otp)

	if len(ret) == 0 {
		panic("no return value specified for ValidateOTP")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, intermediateJWT, otp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, intermediateJWT, otp)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, intermediateJWT, otp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_ValidateOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateOTP'
type MockAccountAPI_ValidateOTP_Call struct {
	*mock.Call
}

// ValidateOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - intermediateJWT string
//   - otp string
func (_e *MockAccountAPI_Expecter) ValidateOTP(ctx interface{}, intermediateJWT interface{}, otp interface{}) *MockAccountAPI_ValidateOTP_Call {
	return &MockAccountAPI_ValidateOTP_Call{Call: _e.mock.On("ValidateOTP", ctx, intermediateJWT, otp)}
}

func (_c *MockAccountAPI_ValidateOTP_Call) Run(run func(ctx context.Context, intermediateJWT string, otp string)) *MockAccountAPI_ValidateOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountAPI_ValidateOTP_Call) Return(s string, err error) *MockAccountAPI_ValidateOTP_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAccountAPI_ValidateOTP_Call) RunAndReturn(run func(ctx context.Context, intermediateJWT string, otp string) (string, error)) *MockAccountAPI_ValidateOTP_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) VerifyEmail(ctx context.Context, email string, token string) error {
	ret := _mock.Called(ctx, email, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type MockAccountAPI_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - token string
func (_e *MockAccountAPI_Expecter) VerifyEmail(ctx interface{}, email interface{}, token interface{}) *MockAccountAPI_VerifyEmail_Call {
	return &MockAccountAPI_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, email, token)}
}

func (_c *MockAccountAPI_VerifyEmail_Call) Run(run func(ctx context.Context, email string, token string)) *MockAccountAPI_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountAPI_VerifyEmail_Call) Return(err error) *MockAccountAPI_VerifyEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_VerifyEmail_Call) RunAndReturn(run func(ctx context.Context, email string, token string) error) *MockAccountAPI_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOTP provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) VerifyOTP(ctx context.Context, otp string) error {
	ret := _mock.Called(ctx, otp)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, otp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountAPI_VerifyOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOTP'
type MockAccountAPI_VerifyOTP_Call struct {
	*mock.Call
}

// VerifyOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - otp string
func (_e *MockAccountAPI_Expecter) VerifyOTP(ctx interface{}, otp interface{}) *MockAccountAPI_VerifyOTP_Call {
	return &MockAccountAPI_VerifyOTP_Call{Call: _e.mock.On("VerifyOTP", ctx, otp)}
}

func (_c *MockAccountAPI_VerifyOTP_Call) Run(run func(ctx context.Context, otp string)) *MockAccountAPI_VerifyOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountAPI_VerifyOTP_Call) Return(err error) *MockAccountAPI_VerifyOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountAPI_VerifyOTP_Call) RunAndReturn(run func(ctx context.Context, otp string) error) *MockAccountAPI_VerifyOTP_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForOperation provides a mock function for the type MockAccountAPI
func (_mock *MockAccountAPI) WaitForOperation(ctx context.Context, id int64, opts ...account.PollOption) (*account.Operation, error) {
	// account.PollOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WaitForOperation")
	}

	var r0 *account.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, ...account.PollOption) (*account.Operation, error)); ok {
		return returnFunc(ctx, id, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, ...account.PollOption) *account.Operation); ok {
		r0 = returnFunc(ctx, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, ...account.PollOption) error); ok {
		r1 = returnFunc(ctx, id, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountAPI_WaitForOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForOperation'
type MockAccountAPI_WaitForOperation_Call struct {
	*mock.Call
}

// WaitForOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - opts ...account.PollOption
func (_e *MockAccountAPI_Expecter) WaitForOperation(ctx interface{}, id interface{}, opts ...interface{}) *MockAccountAPI_WaitForOperation_Call {
	return &MockAccountAPI_WaitForOperation_Call{Call: _e.mock.On("WaitForOperation",
		append([]interface{}{ctx, id}, opts...)...)}
}

func (_c *MockAccountAPI_WaitForOperation_Call) Run(run func(ctx context.Context, id int64, opts ...account.PollOption)) *MockAccountAPI_WaitForOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []account.PollOption
		variadicArgs := make([]account.PollOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(account.PollOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAccountAPI_WaitForOperation_Call) Return(operation *account.Operation, err error) *MockAccountAPI_WaitForOperation_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *MockAccountAPI_WaitForOperation_Call) RunAndReturn(run func(ctx context.Context, id int64, opts ...account.PollOption) (*account.Operation, error)) *MockAccountAPI_WaitForOperation_Call {
	_c.Call.Return(run)
	return _c
}
