// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	meta "go.lumeweb.com/portal-sdk/internal/meta"
)

// MockClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type MockClientWithResponsesInterface struct {
	mock.Mock
}

type MockClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterface_Expecter {
	return &MockClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// GetApiExportCidCidDagWithResponse provides a mock function with given fields: ctx, cid, reqEditors
func (_m *MockClientWithResponsesInterface) GetApiExportCidCidDagWithResponse(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn) (*meta.GetApiExportCidCidDagResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, cid)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiExportCidCidDagWithResponse")
	}

	var r0 *meta.GetApiExportCidCidDagResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...meta.RequestEditorFn) (*meta.GetApiExportCidCidDagResponse, error)); ok {
		return rf(ctx, cid, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...meta.RequestEditorFn) *meta.GetApiExportCidCidDagResponse); ok {
		r0 = rf(ctx, cid, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.GetApiExportCidCidDagResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...meta.RequestEditorFn) error); ok {
		r1 = rf(ctx, cid, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiExportCidCidDagWithResponse'
type MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call struct {
	*mock.Call
}

// GetApiExportCidCidDagWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - reqEditors ...meta.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiExportCidCidDagWithResponse(ctx interface{}, cid interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call{Call: _e.mock.On("GetApiExportCidCidDagWithResponse",
		append([]interface{}{ctx, cid}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call) Run(run func(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]meta.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(meta.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call) Return(_a0 *meta.GetApiExportCidCidDagResponse, _a1 error) *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call) RunAndReturn(run func(context.Context, string, ...meta.RequestEditorFn) (*meta.GetApiExportCidCidDagResponse, error)) *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiExportCidCidSiaObjectWithResponse provides a mock function with given fields: ctx, cid, reqEditors
func (_m *MockClientWithResponsesInterface) GetApiExportCidCidSiaObjectWithResponse(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn) (*meta.GetApiExportCidCidSiaObjectResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, cid)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiExportCidCidSiaObjectWithResponse")
	}

	var r0 *meta.GetApiExportCidCidSiaObjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...meta.RequestEditorFn) (*meta.GetApiExportCidCidSiaObjectResponse, error)); ok {
		return rf(ctx, cid, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...meta.RequestEditorFn) *meta.GetApiExportCidCidSiaObjectResponse); ok {
		r0 = rf(ctx, cid, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.GetApiExportCidCidSiaObjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...meta.RequestEditorFn) error); ok {
		r1 = rf(ctx, cid, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiExportCidCidSiaObjectWithResponse'
type MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call struct {
	*mock.Call
}

// GetApiExportCidCidSiaObjectWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - reqEditors ...meta.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiExportCidCidSiaObjectWithResponse(ctx interface{}, cid interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call{Call: _e.mock.On("GetApiExportCidCidSiaObjectWithResponse",
		append([]interface{}{ctx, cid}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call) Run(run func(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]meta.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(meta.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call) Return(_a0 *meta.GetApiExportCidCidSiaObjectResponse, _a1 error) *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call) RunAndReturn(run func(context.Context, string, ...meta.RequestEditorFn) (*meta.GetApiExportCidCidSiaObjectResponse, error)) *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiStatsAggregateWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *MockClientWithResponsesInterface) GetApiStatsAggregateWithResponse(ctx context.Context, reqEditors ...meta.RequestEditorFn) (*meta.GetApiStatsAggregateResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiStatsAggregateWithResponse")
	}

	var r0 *meta.GetApiStatsAggregateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...meta.RequestEditorFn) (*meta.GetApiStatsAggregateResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...meta.RequestEditorFn) *meta.GetApiStatsAggregateResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.GetApiStatsAggregateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...meta.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiStatsAggregateWithResponse'
type MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call struct {
	*mock.Call
}

// GetApiStatsAggregateWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...meta.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiStatsAggregateWithResponse(ctx interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call{Call: _e.mock.On("GetApiStatsAggregateWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...meta.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]meta.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(meta.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call) Return(_a0 *meta.GetApiStatsAggregateResponse, _a1 error) *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call) RunAndReturn(run func(context.Context, ...meta.RequestEditorFn) (*meta.GetApiStatsAggregateResponse, error)) *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiStatsCidCidWithResponse provides a mock function with given fields: ctx, cid, reqEditors
func (_m *MockClientWithResponsesInterface) GetApiStatsCidCidWithResponse(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn) (*meta.GetApiStatsCidCidResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, cid)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiStatsCidCidWithResponse")
	}

	var r0 *meta.GetApiStatsCidCidResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...meta.RequestEditorFn) (*meta.GetApiStatsCidCidResponse, error)); ok {
		return rf(ctx, cid, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...meta.RequestEditorFn) *meta.GetApiStatsCidCidResponse); ok {
		r0 = rf(ctx, cid, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.GetApiStatsCidCidResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...meta.RequestEditorFn) error); ok {
		r1 = rf(ctx, cid, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiStatsCidCidWithResponse'
type MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call struct {
	*mock.Call
}

// GetApiStatsCidCidWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - reqEditors ...meta.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiStatsCidCidWithResponse(ctx interface{}, cid interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call{Call: _e.mock.On("GetApiStatsCidCidWithResponse",
		append([]interface{}{ctx, cid}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call) Run(run func(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]meta.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(meta.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call) Return(_a0 *meta.GetApiStatsCidCidResponse, _a1 error) *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call) RunAndReturn(run func(context.Context, string, ...meta.RequestEditorFn) (*meta.GetApiStatsCidCidResponse, error)) *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiStatsProtocolsWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *MockClientWithResponsesInterface) GetApiStatsProtocolsWithResponse(ctx context.Context, reqEditors ...meta.RequestEditorFn) (*meta.GetApiStatsProtocolsResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiStatsProtocolsWithResponse")
	}

	var r0 *meta.GetApiStatsProtocolsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...meta.RequestEditorFn) (*meta.GetApiStatsProtocolsResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...meta.RequestEditorFn) *meta.GetApiStatsProtocolsResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.GetApiStatsProtocolsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...meta.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiStatsProtocolsWithResponse'
type MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call struct {
	*mock.Call
}

// GetApiStatsProtocolsWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...meta.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiStatsProtocolsWithResponse(ctx interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call{Call: _e.mock.On("GetApiStatsProtocolsWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...meta.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]meta.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(meta.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call) Return(_a0 *meta.GetApiStatsProtocolsResponse, _a1 error) *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call) RunAndReturn(run func(context.Context, ...meta.RequestEditorFn) (*meta.GetApiStatsProtocolsResponse, error)) *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientWithResponsesInterface creates a new instance of MockClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
