// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-sdk/internal/meta"
)

// NewMockClientWithResponsesInterface creates a new instance of MockClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type MockClientWithResponsesInterface struct {
	mock.Mock
}

type MockClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterface_Expecter {
	return &MockClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// GetApiExportCidCidDagWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) GetApiExportCidCidDagWithResponse(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn) (*meta.GetApiExportCidCidDagResponse, error) {
	// meta.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, cid)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiExportCidCidDagWithResponse")
	}

	var r0 *meta.GetApiExportCidCidDagResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...meta.RequestEditorFn) (*meta.GetApiExportCidCidDagResponse, error)); ok {
		return returnFunc(ctx, cid, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...meta.RequestEditorFn) *meta.GetApiExportCidCidDagResponse); ok {
		r0 = returnFunc(ctx, cid, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.GetApiExportCidCidDagResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...meta.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, cid, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiExportCidCidDagWithResponse'
type MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call struct {
	*mock.Call
}

// GetApiExportCidCidDagWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - reqEditors ...meta.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiExportCidCidDagWithResponse(ctx any, cid any, reqEditors ...any) *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call{Call: _e.mock.On("GetApiExportCidCidDagWithResponse",
		append([]any{ctx, cid}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call) Run(run func(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []meta.RequestEditorFn
		variadicArgs := make([]meta.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(meta.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call) Return(getApiExportCidCidDagResponse *meta.GetApiExportCidCidDagResponse, err error) *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call {
	_c.Call.Return(getApiExportCidCidDagResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call) RunAndReturn(run func(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn) (*meta.GetApiExportCidCidDagResponse, error)) *MockClientWithResponsesInterface_GetApiExportCidCidDagWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiExportCidCidSiaObjectWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) GetApiExportCidCidSiaObjectWithResponse(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn) (*meta.GetApiExportCidCidSiaObjectResponse, error) {
	// meta.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, cid)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiExportCidCidSiaObjectWithResponse")
	}

	var r0 *meta.GetApiExportCidCidSiaObjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...meta.RequestEditorFn) (*meta.GetApiExportCidCidSiaObjectResponse, error)); ok {
		return returnFunc(ctx, cid, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...meta.RequestEditorFn) *meta.GetApiExportCidCidSiaObjectResponse); ok {
		r0 = returnFunc(ctx, cid, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.GetApiExportCidCidSiaObjectResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...meta.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, cid, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiExportCidCidSiaObjectWithResponse'
type MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call struct {
	*mock.Call
}

// GetApiExportCidCidSiaObjectWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - reqEditors ...meta.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiExportCidCidSiaObjectWithResponse(ctx any, cid any, reqEditors ...any) *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call{Call: _e.mock.On("GetApiExportCidCidSiaObjectWithResponse",
		append([]any{ctx, cid}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call) Run(run func(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []meta.RequestEditorFn
		variadicArgs := make([]meta.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(meta.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call) Return(getApiExportCidCidSiaObjectResponse *meta.GetApiExportCidCidSiaObjectResponse, err error) *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call {
	_c.Call.Return(getApiExportCidCidSiaObjectResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call) RunAndReturn(run func(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn) (*meta.GetApiExportCidCidSiaObjectResponse, error)) *MockClientWithResponsesInterface_GetApiExportCidCidSiaObjectWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiStatsAggregateWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) GetApiStatsAggregateWithResponse(ctx context.Context, reqEditors ...meta.RequestEditorFn) (*meta.GetApiStatsAggregateResponse, error) {
	// meta.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiStatsAggregateWithResponse")
	}

	var r0 *meta.GetApiStatsAggregateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...meta.RequestEditorFn) (*meta.GetApiStatsAggregateResponse, error)); ok {
		return returnFunc(ctx, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...meta.RequestEditorFn) *meta.GetApiStatsAggregateResponse); ok {
		r0 = returnFunc(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.GetApiStatsAggregateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...meta.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiStatsAggregateWithResponse'
type MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call struct {
	*mock.Call
}

// GetApiStatsAggregateWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...meta.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiStatsAggregateWithResponse(ctx any, reqEditors ...any) *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call{Call: _e.mock.On("GetApiStatsAggregateWithResponse",
		append([]any{ctx}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...meta.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []meta.RequestEditorFn
		variadicArgs := make([]meta.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(meta.RequestEditorFn)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call) Return(getApiStatsAggregateResponse *meta.GetApiStatsAggregateResponse, err error) *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call {
	_c.Call.Return(getApiStatsAggregateResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call) RunAndReturn(run func(ctx context.Context, reqEditors ...meta.RequestEditorFn) (*meta.GetApiStatsAggregateResponse, error)) *MockClientWithResponsesInterface_GetApiStatsAggregateWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiStatsCidCidWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) GetApiStatsCidCidWithResponse(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn) (*meta.GetApiStatsCidCidResponse, error) {
	// meta.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, cid)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiStatsCidCidWithResponse")
	}

	var r0 *meta.GetApiStatsCidCidResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...meta.RequestEditorFn) (*meta.GetApiStatsCidCidResponse, error)); ok {
		return returnFunc(ctx, cid, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...meta.RequestEditorFn) *meta.GetApiStatsCidCidResponse); ok {
		r0 = returnFunc(ctx, cid, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.GetApiStatsCidCidResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...meta.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, cid, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiStatsCidCidWithResponse'
type MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call struct {
	*mock.Call
}

// GetApiStatsCidCidWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - cid string
//   - reqEditors ...meta.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiStatsCidCidWithResponse(ctx any, cid any, reqEditors ...any) *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call{Call: _e.mock.On("GetApiStatsCidCidWithResponse",
		append([]any{ctx, cid}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call) Run(run func(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []meta.RequestEditorFn
		variadicArgs := make([]meta.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(meta.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call) Return(getApiStatsCidCidResponse *meta.GetApiStatsCidCidResponse, err error) *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call {
	_c.Call.Return(getApiStatsCidCidResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call) RunAndReturn(run func(ctx context.Context, cid string, reqEditors ...meta.RequestEditorFn) (*meta.GetApiStatsCidCidResponse, error)) *MockClientWithResponsesInterface_GetApiStatsCidCidWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiStatsProtocolsWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) GetApiStatsProtocolsWithResponse(ctx context.Context, reqEditors ...meta.RequestEditorFn) (*meta.GetApiStatsProtocolsResponse, error) {
	// meta.RequestEditorFn
	_va := make([]any, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiStatsProtocolsWithResponse")
	}

	var r0 *meta.GetApiStatsProtocolsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...meta.RequestEditorFn) (*meta.GetApiStatsProtocolsResponse, error)); ok {
		return returnFunc(ctx, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...meta.RequestEditorFn) *meta.GetApiStatsProtocolsResponse); ok {
		r0 = returnFunc(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.GetApiStatsProtocolsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...meta.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiStatsProtocolsWithResponse'
type MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call struct {
	*mock.Call
}

// GetApiStatsProtocolsWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...meta.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiStatsProtocolsWithResponse(ctx any, reqEditors ...any) *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call{Call: _e.mock.On("GetApiStatsProtocolsWithResponse",
		append([]any{ctx}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...meta.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []meta.RequestEditorFn
		variadicArgs := make([]meta.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(meta.RequestEditorFn)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call) Return(getApiStatsProtocolsResponse *meta.GetApiStatsProtocolsResponse, err error) *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call {
	_c.Call.Return(getApiStatsProtocolsResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call) RunAndReturn(run func(ctx context.Context, reqEditors ...meta.RequestEditorFn) (*meta.GetApiStatsProtocolsResponse, error)) *MockClientWithResponsesInterface_GetApiStatsProtocolsWithResponse_Call {
	_c.Call.Return(run)
	return _c
}
