// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-sdk/internal/admin"
)

// NewMockClientWithResponsesInterface creates a new instance of MockClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type MockClientWithResponsesInterface struct {
	mock.Mock
}

type MockClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterface_Expecter {
	return &MockClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// DeleteApiQuotaAllowancesGrantIDWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) DeleteApiQuotaAllowancesGrantIDWithResponse(ctx context.Context, grantID string, reqEditors ...admin.RequestEditorFn) (*admin.DeleteApiQuotaAllowancesGrantIDResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, grantID)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApiQuotaAllowancesGrantIDWithResponse")
	}

	var r0 *admin.DeleteApiQuotaAllowancesGrantIDResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...admin.RequestEditorFn) (*admin.DeleteApiQuotaAllowancesGrantIDResponse, error)); ok {
		return returnFunc(ctx, grantID, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...admin.RequestEditorFn) *admin.DeleteApiQuotaAllowancesGrantIDResponse); ok {
		r0 = returnFunc(ctx, grantID, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.DeleteApiQuotaAllowancesGrantIDResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, grantID, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_DeleteApiQuotaAllowancesGrantIDWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApiQuotaAllowancesGrantIDWithResponse'
type MockClientWithResponsesInterface_DeleteApiQuotaAllowancesGrantIDWithResponse_Call struct {
	*mock.Call
}

// DeleteApiQuotaAllowancesGrantIDWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - grantID string
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) DeleteApiQuotaAllowancesGrantIDWithResponse(ctx interface{}, grantID interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_DeleteApiQuotaAllowancesGrantIDWithResponse_Call {
	return &MockClientWithResponsesInterface_DeleteApiQuotaAllowancesGrantIDWithResponse_Call{Call: _e.mock.On("DeleteApiQuotaAllowancesGrantIDWithResponse",
		append([]interface{}{ctx, grantID}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_DeleteApiQuotaAllowancesGrantIDWithResponse_Call) Run(run func(ctx context.Context, grantID string, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_DeleteApiQuotaAllowancesGrantIDWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_DeleteApiQuotaAllowancesGrantIDWithResponse_Call) Return(deleteApiQuotaAllowancesGrantIDResponse *admin.DeleteApiQuotaAllowancesGrantIDResponse, err error) *MockClientWithResponsesInterface_DeleteApiQuotaAllowancesGrantIDWithResponse_Call {
	_c.Call.Return(deleteApiQuotaAllowancesGrantIDResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_DeleteApiQuotaAllowancesGrantIDWithResponse_Call) RunAndReturn(run func(ctx context.Context, grantID string, reqEditors ...admin.RequestEditorFn) (*admin.DeleteApiQuotaAllowancesGrantIDResponse, error)) *MockClientWithResponsesInterface_DeleteApiQuotaAllowancesGrantIDWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteApiQuotaPlansPlanIDWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) DeleteApiQuotaPlansPlanIDWithResponse(ctx context.Context, planID string, reqEditors ...admin.RequestEditorFn) (*admin.DeleteApiQuotaPlansPlanIDResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, planID)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApiQuotaPlansPlanIDWithResponse")
	}

	var r0 *admin.DeleteApiQuotaPlansPlanIDResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...admin.RequestEditorFn) (*admin.DeleteApiQuotaPlansPlanIDResponse, error)); ok {
		return returnFunc(ctx, planID, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...admin.RequestEditorFn) *admin.DeleteApiQuotaPlansPlanIDResponse); ok {
		r0 = returnFunc(ctx, planID, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.DeleteApiQuotaPlansPlanIDResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, planID, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_DeleteApiQuotaPlansPlanIDWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApiQuotaPlansPlanIDWithResponse'
type MockClientWithResponsesInterface_DeleteApiQuotaPlansPlanIDWithResponse_Call struct {
	*mock.Call
}

// DeleteApiQuotaPlansPlanIDWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) DeleteApiQuotaPlansPlanIDWithResponse(ctx interface{}, planID interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_DeleteApiQuotaPlansPlanIDWithResponse_Call {
	return &MockClientWithResponsesInterface_DeleteApiQuotaPlansPlanIDWithResponse_Call{Call: _e.mock.On("DeleteApiQuotaPlansPlanIDWithResponse",
		append([]interface{}{ctx, planID}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_DeleteApiQuotaPlansPlanIDWithResponse_Call) Run(run func(ctx context.Context, planID string, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_DeleteApiQuotaPlansPlanIDWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_DeleteApiQuotaPlansPlanIDWithResponse_Call) Return(deleteApiQuotaPlansPlanIDResponse *admin.DeleteApiQuotaPlansPlanIDResponse, err error) *MockClientWithResponsesInterface_DeleteApiQuotaPlansPlanIDWithResponse_Call {
	_c.Call.Return(deleteApiQuotaPlansPlanIDResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_DeleteApiQuotaPlansPlanIDWithResponse_Call) RunAndReturn(run func(ctx context.Context, planID string, reqEditors ...admin.RequestEditorFn) (*admin.DeleteApiQuotaPlansPlanIDResponse, error)) *MockClientWithResponsesInterface_DeleteApiQuotaPlansPlanIDWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiQuotaAllowancesWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) GetApiQuotaAllowancesWithResponse(ctx context.Context, reqEditors ...admin.RequestEditorFn) (*admin.GetApiQuotaAllowancesResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiQuotaAllowancesWithResponse")
	}

	var r0 *admin.GetApiQuotaAllowancesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...admin.RequestEditorFn) (*admin.GetApiQuotaAllowancesResponse, error)); ok {
		return returnFunc(ctx, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...admin.RequestEditorFn) *admin.GetApiQuotaAllowancesResponse); ok {
		r0 = returnFunc(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.GetApiQuotaAllowancesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_GetApiQuotaAllowancesWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiQuotaAllowancesWithResponse'
type MockClientWithResponsesInterface_GetApiQuotaAllowancesWithResponse_Call struct {
	*mock.Call
}

// GetApiQuotaAllowancesWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiQuotaAllowancesWithResponse(ctx interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_GetApiQuotaAllowancesWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiQuotaAllowancesWithResponse_Call{Call: _e.mock.On("GetApiQuotaAllowancesWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaAllowancesWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiQuotaAllowancesWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaAllowancesWithResponse_Call) Return(getApiQuotaAllowancesResponse *admin.GetApiQuotaAllowancesResponse, err error) *MockClientWithResponsesInterface_GetApiQuotaAllowancesWithResponse_Call {
	_c.Call.Return(getApiQuotaAllowancesResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaAllowancesWithResponse_Call) RunAndReturn(run func(ctx context.Context, reqEditors ...admin.RequestEditorFn) (*admin.GetApiQuotaAllowancesResponse, error)) *MockClientWithResponsesInterface_GetApiQuotaAllowancesWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiQuotaPlansPlanIDWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) GetApiQuotaPlansPlanIDWithResponse(ctx context.Context, planID string, reqEditors ...admin.RequestEditorFn) (*admin.GetApiQuotaPlansPlanIDResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, planID)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiQuotaPlansPlanIDWithResponse")
	}

	var r0 *admin.GetApiQuotaPlansPlanIDResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...admin.RequestEditorFn) (*admin.GetApiQuotaPlansPlanIDResponse, error)); ok {
		return returnFunc(ctx, planID, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...admin.RequestEditorFn) *admin.GetApiQuotaPlansPlanIDResponse); ok {
		r0 = returnFunc(ctx, planID, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.GetApiQuotaPlansPlanIDResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, planID, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_GetApiQuotaPlansPlanIDWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiQuotaPlansPlanIDWithResponse'
type MockClientWithResponsesInterface_GetApiQuotaPlansPlanIDWithResponse_Call struct {
	*mock.Call
}

// GetApiQuotaPlansPlanIDWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiQuotaPlansPlanIDWithResponse(ctx interface{}, planID interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_GetApiQuotaPlansPlanIDWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiQuotaPlansPlanIDWithResponse_Call{Call: _e.mock.On("GetApiQuotaPlansPlanIDWithResponse",
		append([]interface{}{ctx, planID}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaPlansPlanIDWithResponse_Call) Run(run func(ctx context.Context, planID string, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiQuotaPlansPlanIDWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaPlansPlanIDWithResponse_Call) Return(getApiQuotaPlansPlanIDResponse *admin.GetApiQuotaPlansPlanIDResponse, err error) *MockClientWithResponsesInterface_GetApiQuotaPlansPlanIDWithResponse_Call {
	_c.Call.Return(getApiQuotaPlansPlanIDResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaPlansPlanIDWithResponse_Call) RunAndReturn(run func(ctx context.Context, planID string, reqEditors ...admin.RequestEditorFn) (*admin.GetApiQuotaPlansPlanIDResponse, error)) *MockClientWithResponsesInterface_GetApiQuotaPlansPlanIDWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiQuotaPlansWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) GetApiQuotaPlansWithResponse(ctx context.Context, reqEditors ...admin.RequestEditorFn) (*admin.GetApiQuotaPlansResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiQuotaPlansWithResponse")
	}

	var r0 *admin.GetApiQuotaPlansResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...admin.RequestEditorFn) (*admin.GetApiQuotaPlansResponse, error)); ok {
		return returnFunc(ctx, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...admin.RequestEditorFn) *admin.GetApiQuotaPlansResponse); ok {
		r0 = returnFunc(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.GetApiQuotaPlansResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_GetApiQuotaPlansWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiQuotaPlansWithResponse'
type MockClientWithResponsesInterface_GetApiQuotaPlansWithResponse_Call struct {
	*mock.Call
}

// GetApiQuotaPlansWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiQuotaPlansWithResponse(ctx interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_GetApiQuotaPlansWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiQuotaPlansWithResponse_Call{Call: _e.mock.On("GetApiQuotaPlansWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaPlansWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiQuotaPlansWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaPlansWithResponse_Call) Return(getApiQuotaPlansResponse *admin.GetApiQuotaPlansResponse, err error) *MockClientWithResponsesInterface_GetApiQuotaPlansWithResponse_Call {
	_c.Call.Return(getApiQuotaPlansResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaPlansWithResponse_Call) RunAndReturn(run func(ctx context.Context, reqEditors ...admin.RequestEditorFn) (*admin.GetApiQuotaPlansResponse, error)) *MockClientWithResponsesInterface_GetApiQuotaPlansWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiQuotaSystemConfigWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) GetApiQuotaSystemConfigWithResponse(ctx context.Context, reqEditors ...admin.RequestEditorFn) (*admin.GetApiQuotaSystemConfigResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiQuotaSystemConfigWithResponse")
	}

	var r0 *admin.GetApiQuotaSystemConfigResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...admin.RequestEditorFn) (*admin.GetApiQuotaSystemConfigResponse, error)); ok {
		return returnFunc(ctx, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...admin.RequestEditorFn) *admin.GetApiQuotaSystemConfigResponse); ok {
		r0 = returnFunc(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.GetApiQuotaSystemConfigResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_GetApiQuotaSystemConfigWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiQuotaSystemConfigWithResponse'
type MockClientWithResponsesInterface_GetApiQuotaSystemConfigWithResponse_Call struct {
	*mock.Call
}

// GetApiQuotaSystemConfigWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiQuotaSystemConfigWithResponse(ctx interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_GetApiQuotaSystemConfigWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiQuotaSystemConfigWithResponse_Call{Call: _e.mock.On("GetApiQuotaSystemConfigWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaSystemConfigWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiQuotaSystemConfigWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaSystemConfigWithResponse_Call) Return(getApiQuotaSystemConfigResponse *admin.GetApiQuotaSystemConfigResponse, err error) *MockClientWithResponsesInterface_GetApiQuotaSystemConfigWithResponse_Call {
	_c.Call.Return(getApiQuotaSystemConfigResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaSystemConfigWithResponse_Call) RunAndReturn(run func(ctx context.Context, reqEditors ...admin.RequestEditorFn) (*admin.GetApiQuotaSystemConfigResponse, error)) *MockClientWithResponsesInterface_GetApiQuotaSystemConfigWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetApiQuotaSystemStatsWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) GetApiQuotaSystemStatsWithResponse(ctx context.Context, reqEditors ...admin.RequestEditorFn) (*admin.GetApiQuotaSystemStatsResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetApiQuotaSystemStatsWithResponse")
	}

	var r0 *admin.GetApiQuotaSystemStatsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...admin.RequestEditorFn) (*admin.GetApiQuotaSystemStatsResponse, error)); ok {
		return returnFunc(ctx, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...admin.RequestEditorFn) *admin.GetApiQuotaSystemStatsResponse); ok {
		r0 = returnFunc(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.GetApiQuotaSystemStatsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_GetApiQuotaSystemStatsWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiQuotaSystemStatsWithResponse'
type MockClientWithResponsesInterface_GetApiQuotaSystemStatsWithResponse_Call struct {
	*mock.Call
}

// GetApiQuotaSystemStatsWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetApiQuotaSystemStatsWithResponse(ctx interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_GetApiQuotaSystemStatsWithResponse_Call {
	return &MockClientWithResponsesInterface_GetApiQuotaSystemStatsWithResponse_Call{Call: _e.mock.On("GetApiQuotaSystemStatsWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaSystemStatsWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_GetApiQuotaSystemStatsWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaSystemStatsWithResponse_Call) Return(getApiQuotaSystemStatsResponse *admin.GetApiQuotaSystemStatsResponse, err error) *MockClientWithResponsesInterface_GetApiQuotaSystemStatsWithResponse_Call {
	_c.Call.Return(getApiQuotaSystemStatsResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetApiQuotaSystemStatsWithResponse_Call) RunAndReturn(run func(ctx context.Context, reqEditors ...admin.RequestEditorFn) (*admin.GetApiQuotaSystemStatsResponse, error)) *MockClientWithResponsesInterface_GetApiQuotaSystemStatsWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiQuotaAllowancesWithBodyWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PostApiQuotaAllowancesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaAllowancesResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiQuotaAllowancesWithBodyWithResponse")
	}

	var r0 *admin.PostApiQuotaAllowancesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) (*admin.PostApiQuotaAllowancesResponse, error)); ok {
		return returnFunc(ctx, contentType, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) *admin.PostApiQuotaAllowancesResponse); ok {
		r0 = returnFunc(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PostApiQuotaAllowancesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PostApiQuotaAllowancesWithBodyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiQuotaAllowancesWithBodyWithResponse'
type MockClientWithResponsesInterface_PostApiQuotaAllowancesWithBodyWithResponse_Call struct {
	*mock.Call
}

// PostApiQuotaAllowancesWithBodyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - body io.Reader
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PostApiQuotaAllowancesWithBodyWithResponse(ctx interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithBodyWithResponse_Call {
	return &MockClientWithResponsesInterface_PostApiQuotaAllowancesWithBodyWithResponse_Call{Call: _e.mock.On("PostApiQuotaAllowancesWithBodyWithResponse",
		append([]interface{}{ctx, contentType, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithBodyWithResponse_Call) Run(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithBodyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithBodyWithResponse_Call) Return(postApiQuotaAllowancesResponse *admin.PostApiQuotaAllowancesResponse, err error) *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithBodyWithResponse_Call {
	_c.Call.Return(postApiQuotaAllowancesResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithBodyWithResponse_Call) RunAndReturn(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaAllowancesResponse, error)) *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithBodyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiQuotaAllowancesWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PostApiQuotaAllowancesWithResponse(ctx context.Context, body admin.PostApiQuotaAllowancesJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaAllowancesResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiQuotaAllowancesWithResponse")
	}

	var r0 *admin.PostApiQuotaAllowancesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.PostApiQuotaAllowancesJSONRequestBody, ...admin.RequestEditorFn) (*admin.PostApiQuotaAllowancesResponse, error)); ok {
		return returnFunc(ctx, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.PostApiQuotaAllowancesJSONRequestBody, ...admin.RequestEditorFn) *admin.PostApiQuotaAllowancesResponse); ok {
		r0 = returnFunc(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PostApiQuotaAllowancesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, admin.PostApiQuotaAllowancesJSONRequestBody, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PostApiQuotaAllowancesWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiQuotaAllowancesWithResponse'
type MockClientWithResponsesInterface_PostApiQuotaAllowancesWithResponse_Call struct {
	*mock.Call
}

// PostApiQuotaAllowancesWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - body admin.PostApiQuotaAllowancesJSONRequestBody
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PostApiQuotaAllowancesWithResponse(ctx interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithResponse_Call {
	return &MockClientWithResponsesInterface_PostApiQuotaAllowancesWithResponse_Call{Call: _e.mock.On("PostApiQuotaAllowancesWithResponse",
		append([]interface{}{ctx, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithResponse_Call) Run(run func(ctx context.Context, body admin.PostApiQuotaAllowancesJSONRequestBody, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 admin.PostApiQuotaAllowancesJSONRequestBody
		if args[1] != nil {
			arg1 = args[1].(admin.PostApiQuotaAllowancesJSONRequestBody)
		}
		var arg2 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithResponse_Call) Return(postApiQuotaAllowancesResponse *admin.PostApiQuotaAllowancesResponse, err error) *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithResponse_Call {
	_c.Call.Return(postApiQuotaAllowancesResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithResponse_Call) RunAndReturn(run func(ctx context.Context, body admin.PostApiQuotaAllowancesJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaAllowancesResponse, error)) *MockClientWithResponsesInterface_PostApiQuotaAllowancesWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiQuotaPlansPlanIDDefaultWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PostApiQuotaPlansPlanIDDefaultWithResponse(ctx context.Context, planID string, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaPlansPlanIDDefaultResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, planID)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiQuotaPlansPlanIDDefaultWithResponse")
	}

	var r0 *admin.PostApiQuotaPlansPlanIDDefaultResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...admin.RequestEditorFn) (*admin.PostApiQuotaPlansPlanIDDefaultResponse, error)); ok {
		return returnFunc(ctx, planID, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...admin.RequestEditorFn) *admin.PostApiQuotaPlansPlanIDDefaultResponse); ok {
		r0 = returnFunc(ctx, planID, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PostApiQuotaPlansPlanIDDefaultResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, planID, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PostApiQuotaPlansPlanIDDefaultWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiQuotaPlansPlanIDDefaultWithResponse'
type MockClientWithResponsesInterface_PostApiQuotaPlansPlanIDDefaultWithResponse_Call struct {
	*mock.Call
}

// PostApiQuotaPlansPlanIDDefaultWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PostApiQuotaPlansPlanIDDefaultWithResponse(ctx interface{}, planID interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PostApiQuotaPlansPlanIDDefaultWithResponse_Call {
	return &MockClientWithResponsesInterface_PostApiQuotaPlansPlanIDDefaultWithResponse_Call{Call: _e.mock.On("PostApiQuotaPlansPlanIDDefaultWithResponse",
		append([]interface{}{ctx, planID}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaPlansPlanIDDefaultWithResponse_Call) Run(run func(ctx context.Context, planID string, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PostApiQuotaPlansPlanIDDefaultWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaPlansPlanIDDefaultWithResponse_Call) Return(postApiQuotaPlansPlanIDDefaultResponse *admin.PostApiQuotaPlansPlanIDDefaultResponse, err error) *MockClientWithResponsesInterface_PostApiQuotaPlansPlanIDDefaultWithResponse_Call {
	_c.Call.Return(postApiQuotaPlansPlanIDDefaultResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaPlansPlanIDDefaultWithResponse_Call) RunAndReturn(run func(ctx context.Context, planID string, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaPlansPlanIDDefaultResponse, error)) *MockClientWithResponsesInterface_PostApiQuotaPlansPlanIDDefaultWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiQuotaPlansWithBodyWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PostApiQuotaPlansWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaPlansResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiQuotaPlansWithBodyWithResponse")
	}

	var r0 *admin.PostApiQuotaPlansResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) (*admin.PostApiQuotaPlansResponse, error)); ok {
		return returnFunc(ctx, contentType, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) *admin.PostApiQuotaPlansResponse); ok {
		r0 = returnFunc(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PostApiQuotaPlansResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PostApiQuotaPlansWithBodyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiQuotaPlansWithBodyWithResponse'
type MockClientWithResponsesInterface_PostApiQuotaPlansWithBodyWithResponse_Call struct {
	*mock.Call
}

// PostApiQuotaPlansWithBodyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - body io.Reader
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PostApiQuotaPlansWithBodyWithResponse(ctx interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PostApiQuotaPlansWithBodyWithResponse_Call {
	return &MockClientWithResponsesInterface_PostApiQuotaPlansWithBodyWithResponse_Call{Call: _e.mock.On("PostApiQuotaPlansWithBodyWithResponse",
		append([]interface{}{ctx, contentType, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaPlansWithBodyWithResponse_Call) Run(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PostApiQuotaPlansWithBodyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaPlansWithBodyWithResponse_Call) Return(postApiQuotaPlansResponse *admin.PostApiQuotaPlansResponse, err error) *MockClientWithResponsesInterface_PostApiQuotaPlansWithBodyWithResponse_Call {
	_c.Call.Return(postApiQuotaPlansResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaPlansWithBodyWithResponse_Call) RunAndReturn(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaPlansResponse, error)) *MockClientWithResponsesInterface_PostApiQuotaPlansWithBodyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiQuotaPlansWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PostApiQuotaPlansWithResponse(ctx context.Context, body admin.PostApiQuotaPlansJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaPlansResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiQuotaPlansWithResponse")
	}

	var r0 *admin.PostApiQuotaPlansResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.PostApiQuotaPlansJSONRequestBody, ...admin.RequestEditorFn) (*admin.PostApiQuotaPlansResponse, error)); ok {
		return returnFunc(ctx, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.PostApiQuotaPlansJSONRequestBody, ...admin.RequestEditorFn) *admin.PostApiQuotaPlansResponse); ok {
		r0 = returnFunc(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PostApiQuotaPlansResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, admin.PostApiQuotaPlansJSONRequestBody, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PostApiQuotaPlansWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiQuotaPlansWithResponse'
type MockClientWithResponsesInterface_PostApiQuotaPlansWithResponse_Call struct {
	*mock.Call
}

// PostApiQuotaPlansWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - body admin.PostApiQuotaPlansJSONRequestBody
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PostApiQuotaPlansWithResponse(ctx interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PostApiQuotaPlansWithResponse_Call {
	return &MockClientWithResponsesInterface_PostApiQuotaPlansWithResponse_Call{Call: _e.mock.On("PostApiQuotaPlansWithResponse",
		append([]interface{}{ctx, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaPlansWithResponse_Call) Run(run func(ctx context.Context, body admin.PostApiQuotaPlansJSONRequestBody, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PostApiQuotaPlansWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 admin.PostApiQuotaPlansJSONRequestBody
		if args[1] != nil {
			arg1 = args[1].(admin.PostApiQuotaPlansJSONRequestBody)
		}
		var arg2 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaPlansWithResponse_Call) Return(postApiQuotaPlansResponse *admin.PostApiQuotaPlansResponse, err error) *MockClientWithResponsesInterface_PostApiQuotaPlansWithResponse_Call {
	_c.Call.Return(postApiQuotaPlansResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaPlansWithResponse_Call) RunAndReturn(run func(ctx context.Context, body admin.PostApiQuotaPlansJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaPlansResponse, error)) *MockClientWithResponsesInterface_PostApiQuotaPlansWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiQuotaSystemCleanupWithBodyWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PostApiQuotaSystemCleanupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaSystemCleanupResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiQuotaSystemCleanupWithBodyWithResponse")
	}

	var r0 *admin.PostApiQuotaSystemCleanupResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) (*admin.PostApiQuotaSystemCleanupResponse, error)); ok {
		return returnFunc(ctx, contentType, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) *admin.PostApiQuotaSystemCleanupResponse); ok {
		r0 = returnFunc(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PostApiQuotaSystemCleanupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithBodyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiQuotaSystemCleanupWithBodyWithResponse'
type MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithBodyWithResponse_Call struct {
	*mock.Call
}

// PostApiQuotaSystemCleanupWithBodyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - body io.Reader
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PostApiQuotaSystemCleanupWithBodyWithResponse(ctx interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithBodyWithResponse_Call {
	return &MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithBodyWithResponse_Call{Call: _e.mock.On("PostApiQuotaSystemCleanupWithBodyWithResponse",
		append([]interface{}{ctx, contentType, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithBodyWithResponse_Call) Run(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithBodyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithBodyWithResponse_Call) Return(postApiQuotaSystemCleanupResponse *admin.PostApiQuotaSystemCleanupResponse, err error) *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithBodyWithResponse_Call {
	_c.Call.Return(postApiQuotaSystemCleanupResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithBodyWithResponse_Call) RunAndReturn(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaSystemCleanupResponse, error)) *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithBodyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiQuotaSystemCleanupWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PostApiQuotaSystemCleanupWithResponse(ctx context.Context, body admin.PostApiQuotaSystemCleanupJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaSystemCleanupResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiQuotaSystemCleanupWithResponse")
	}

	var r0 *admin.PostApiQuotaSystemCleanupResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.PostApiQuotaSystemCleanupJSONRequestBody, ...admin.RequestEditorFn) (*admin.PostApiQuotaSystemCleanupResponse, error)); ok {
		return returnFunc(ctx, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.PostApiQuotaSystemCleanupJSONRequestBody, ...admin.RequestEditorFn) *admin.PostApiQuotaSystemCleanupResponse); ok {
		r0 = returnFunc(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PostApiQuotaSystemCleanupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, admin.PostApiQuotaSystemCleanupJSONRequestBody, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiQuotaSystemCleanupWithResponse'
type MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithResponse_Call struct {
	*mock.Call
}

// PostApiQuotaSystemCleanupWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - body admin.PostApiQuotaSystemCleanupJSONRequestBody
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PostApiQuotaSystemCleanupWithResponse(ctx interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithResponse_Call {
	return &MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithResponse_Call{Call: _e.mock.On("PostApiQuotaSystemCleanupWithResponse",
		append([]interface{}{ctx, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithResponse_Call) Run(run func(ctx context.Context, body admin.PostApiQuotaSystemCleanupJSONRequestBody, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 admin.PostApiQuotaSystemCleanupJSONRequestBody
		if args[1] != nil {
			arg1 = args[1].(admin.PostApiQuotaSystemCleanupJSONRequestBody)
		}
		var arg2 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithResponse_Call) Return(postApiQuotaSystemCleanupResponse *admin.PostApiQuotaSystemCleanupResponse, err error) *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithResponse_Call {
	_c.Call.Return(postApiQuotaSystemCleanupResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithResponse_Call) RunAndReturn(run func(ctx context.Context, body admin.PostApiQuotaSystemCleanupJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaSystemCleanupResponse, error)) *MockClientWithResponsesInterface_PostApiQuotaSystemCleanupWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiQuotaSystemReconcileWithBodyWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PostApiQuotaSystemReconcileWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaSystemReconcileResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiQuotaSystemReconcileWithBodyWithResponse")
	}

	var r0 *admin.PostApiQuotaSystemReconcileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) (*admin.PostApiQuotaSystemReconcileResponse, error)); ok {
		return returnFunc(ctx, contentType, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) *admin.PostApiQuotaSystemReconcileResponse); ok {
		r0 = returnFunc(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PostApiQuotaSystemReconcileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithBodyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiQuotaSystemReconcileWithBodyWithResponse'
type MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithBodyWithResponse_Call struct {
	*mock.Call
}

// PostApiQuotaSystemReconcileWithBodyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - body io.Reader
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PostApiQuotaSystemReconcileWithBodyWithResponse(ctx interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithBodyWithResponse_Call {
	return &MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithBodyWithResponse_Call{Call: _e.mock.On("PostApiQuotaSystemReconcileWithBodyWithResponse",
		append([]interface{}{ctx, contentType, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithBodyWithResponse_Call) Run(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithBodyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithBodyWithResponse_Call) Return(postApiQuotaSystemReconcileResponse *admin.PostApiQuotaSystemReconcileResponse, err error) *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithBodyWithResponse_Call {
	_c.Call.Return(postApiQuotaSystemReconcileResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithBodyWithResponse_Call) RunAndReturn(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaSystemReconcileResponse, error)) *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithBodyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PostApiQuotaSystemReconcileWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PostApiQuotaSystemReconcileWithResponse(ctx context.Context, body admin.PostApiQuotaSystemReconcileJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaSystemReconcileResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostApiQuotaSystemReconcileWithResponse")
	}

	var r0 *admin.PostApiQuotaSystemReconcileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.PostApiQuotaSystemReconcileJSONRequestBody, ...admin.RequestEditorFn) (*admin.PostApiQuotaSystemReconcileResponse, error)); ok {
		return returnFunc(ctx, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.PostApiQuotaSystemReconcileJSONRequestBody, ...admin.RequestEditorFn) *admin.PostApiQuotaSystemReconcileResponse); ok {
		r0 = returnFunc(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PostApiQuotaSystemReconcileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, admin.PostApiQuotaSystemReconcileJSONRequestBody, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostApiQuotaSystemReconcileWithResponse'
type MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithResponse_Call struct {
	*mock.Call
}

// PostApiQuotaSystemReconcileWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - body admin.PostApiQuotaSystemReconcileJSONRequestBody
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PostApiQuotaSystemReconcileWithResponse(ctx interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithResponse_Call {
	return &MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithResponse_Call{Call: _e.mock.On("PostApiQuotaSystemReconcileWithResponse",
		append([]interface{}{ctx, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithResponse_Call) Run(run func(ctx context.Context, body admin.PostApiQuotaSystemReconcileJSONRequestBody, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 admin.PostApiQuotaSystemReconcileJSONRequestBody
		if args[1] != nil {
			arg1 = args[1].(admin.PostApiQuotaSystemReconcileJSONRequestBody)
		}
		var arg2 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithResponse_Call) Return(postApiQuotaSystemReconcileResponse *admin.PostApiQuotaSystemReconcileResponse, err error) *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithResponse_Call {
	_c.Call.Return(postApiQuotaSystemReconcileResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithResponse_Call) RunAndReturn(run func(ctx context.Context, body admin.PostApiQuotaSystemReconcileJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PostApiQuotaSystemReconcileResponse, error)) *MockClientWithResponsesInterface_PostApiQuotaSystemReconcileWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PutApiQuotaAllowancesGrantIDWithBodyWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PutApiQuotaAllowancesGrantIDWithBodyWithResponse(ctx context.Context, grantID string, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PutApiQuotaAllowancesGrantIDResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, grantID, contentType, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutApiQuotaAllowancesGrantIDWithBodyWithResponse")
	}

	var r0 *admin.PutApiQuotaAllowancesGrantIDResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...admin.RequestEditorFn) (*admin.PutApiQuotaAllowancesGrantIDResponse, error)); ok {
		return returnFunc(ctx, grantID, contentType, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...admin.RequestEditorFn) *admin.PutApiQuotaAllowancesGrantIDResponse); ok {
		r0 = returnFunc(ctx, grantID, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PutApiQuotaAllowancesGrantIDResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, grantID, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithBodyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutApiQuotaAllowancesGrantIDWithBodyWithResponse'
type MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithBodyWithResponse_Call struct {
	*mock.Call
}

// PutApiQuotaAllowancesGrantIDWithBodyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - grantID string
//   - contentType string
//   - body io.Reader
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PutApiQuotaAllowancesGrantIDWithBodyWithResponse(ctx interface{}, grantID interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithBodyWithResponse_Call {
	return &MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithBodyWithResponse_Call{Call: _e.mock.On("PutApiQuotaAllowancesGrantIDWithBodyWithResponse",
		append([]interface{}{ctx, grantID, contentType, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithBodyWithResponse_Call) Run(run func(ctx context.Context, grantID string, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithBodyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithBodyWithResponse_Call) Return(putApiQuotaAllowancesGrantIDResponse *admin.PutApiQuotaAllowancesGrantIDResponse, err error) *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithBodyWithResponse_Call {
	_c.Call.Return(putApiQuotaAllowancesGrantIDResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithBodyWithResponse_Call) RunAndReturn(run func(ctx context.Context, grantID string, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PutApiQuotaAllowancesGrantIDResponse, error)) *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithBodyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PutApiQuotaAllowancesGrantIDWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PutApiQuotaAllowancesGrantIDWithResponse(ctx context.Context, grantID string, body admin.PutApiQuotaAllowancesGrantIDJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PutApiQuotaAllowancesGrantIDResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, grantID, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutApiQuotaAllowancesGrantIDWithResponse")
	}

	var r0 *admin.PutApiQuotaAllowancesGrantIDResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, admin.PutApiQuotaAllowancesGrantIDJSONRequestBody, ...admin.RequestEditorFn) (*admin.PutApiQuotaAllowancesGrantIDResponse, error)); ok {
		return returnFunc(ctx, grantID, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, admin.PutApiQuotaAllowancesGrantIDJSONRequestBody, ...admin.RequestEditorFn) *admin.PutApiQuotaAllowancesGrantIDResponse); ok {
		r0 = returnFunc(ctx, grantID, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PutApiQuotaAllowancesGrantIDResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, admin.PutApiQuotaAllowancesGrantIDJSONRequestBody, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, grantID, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutApiQuotaAllowancesGrantIDWithResponse'
type MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithResponse_Call struct {
	*mock.Call
}

// PutApiQuotaAllowancesGrantIDWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - grantID string
//   - body admin.PutApiQuotaAllowancesGrantIDJSONRequestBody
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PutApiQuotaAllowancesGrantIDWithResponse(ctx interface{}, grantID interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithResponse_Call {
	return &MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithResponse_Call{Call: _e.mock.On("PutApiQuotaAllowancesGrantIDWithResponse",
		append([]interface{}{ctx, grantID, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithResponse_Call) Run(run func(ctx context.Context, grantID string, body admin.PutApiQuotaAllowancesGrantIDJSONRequestBody, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 admin.PutApiQuotaAllowancesGrantIDJSONRequestBody
		if args[2] != nil {
			arg2 = args[2].(admin.PutApiQuotaAllowancesGrantIDJSONRequestBody)
		}
		var arg3 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithResponse_Call) Return(putApiQuotaAllowancesGrantIDResponse *admin.PutApiQuotaAllowancesGrantIDResponse, err error) *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithResponse_Call {
	_c.Call.Return(putApiQuotaAllowancesGrantIDResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithResponse_Call) RunAndReturn(run func(ctx context.Context, grantID string, body admin.PutApiQuotaAllowancesGrantIDJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PutApiQuotaAllowancesGrantIDResponse, error)) *MockClientWithResponsesInterface_PutApiQuotaAllowancesGrantIDWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PutApiQuotaPlansPlanIDWithBodyWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PutApiQuotaPlansPlanIDWithBodyWithResponse(ctx context.Context, planID string, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PutApiQuotaPlansPlanIDResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, planID, contentType, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutApiQuotaPlansPlanIDWithBodyWithResponse")
	}

	var r0 *admin.PutApiQuotaPlansPlanIDResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...admin.RequestEditorFn) (*admin.PutApiQuotaPlansPlanIDResponse, error)); ok {
		return returnFunc(ctx, planID, contentType, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...admin.RequestEditorFn) *admin.PutApiQuotaPlansPlanIDResponse); ok {
		r0 = returnFunc(ctx, planID, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PutApiQuotaPlansPlanIDResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, planID, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithBodyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutApiQuotaPlansPlanIDWithBodyWithResponse'
type MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithBodyWithResponse_Call struct {
	*mock.Call
}

// PutApiQuotaPlansPlanIDWithBodyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
//   - contentType string
//   - body io.Reader
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PutApiQuotaPlansPlanIDWithBodyWithResponse(ctx interface{}, planID interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithBodyWithResponse_Call {
	return &MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithBodyWithResponse_Call{Call: _e.mock.On("PutApiQuotaPlansPlanIDWithBodyWithResponse",
		append([]interface{}{ctx, planID, contentType, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithBodyWithResponse_Call) Run(run func(ctx context.Context, planID string, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithBodyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithBodyWithResponse_Call) Return(putApiQuotaPlansPlanIDResponse *admin.PutApiQuotaPlansPlanIDResponse, err error) *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithBodyWithResponse_Call {
	_c.Call.Return(putApiQuotaPlansPlanIDResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithBodyWithResponse_Call) RunAndReturn(run func(ctx context.Context, planID string, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PutApiQuotaPlansPlanIDResponse, error)) *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithBodyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PutApiQuotaPlansPlanIDWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PutApiQuotaPlansPlanIDWithResponse(ctx context.Context, planID string, body admin.PutApiQuotaPlansPlanIDJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PutApiQuotaPlansPlanIDResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, planID, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutApiQuotaPlansPlanIDWithResponse")
	}

	var r0 *admin.PutApiQuotaPlansPlanIDResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, admin.PutApiQuotaPlansPlanIDJSONRequestBody, ...admin.RequestEditorFn) (*admin.PutApiQuotaPlansPlanIDResponse, error)); ok {
		return returnFunc(ctx, planID, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, admin.PutApiQuotaPlansPlanIDJSONRequestBody, ...admin.RequestEditorFn) *admin.PutApiQuotaPlansPlanIDResponse); ok {
		r0 = returnFunc(ctx, planID, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PutApiQuotaPlansPlanIDResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, admin.PutApiQuotaPlansPlanIDJSONRequestBody, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, planID, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutApiQuotaPlansPlanIDWithResponse'
type MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithResponse_Call struct {
	*mock.Call
}

// PutApiQuotaPlansPlanIDWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - planID string
//   - body admin.PutApiQuotaPlansPlanIDJSONRequestBody
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PutApiQuotaPlansPlanIDWithResponse(ctx interface{}, planID interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithResponse_Call {
	return &MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithResponse_Call{Call: _e.mock.On("PutApiQuotaPlansPlanIDWithResponse",
		append([]interface{}{ctx, planID, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithResponse_Call) Run(run func(ctx context.Context, planID string, body admin.PutApiQuotaPlansPlanIDJSONRequestBody, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 admin.PutApiQuotaPlansPlanIDJSONRequestBody
		if args[2] != nil {
			arg2 = args[2].(admin.PutApiQuotaPlansPlanIDJSONRequestBody)
		}
		var arg3 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithResponse_Call) Return(putApiQuotaPlansPlanIDResponse *admin.PutApiQuotaPlansPlanIDResponse, err error) *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithResponse_Call {
	_c.Call.Return(putApiQuotaPlansPlanIDResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithResponse_Call) RunAndReturn(run func(ctx context.Context, planID string, body admin.PutApiQuotaPlansPlanIDJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PutApiQuotaPlansPlanIDResponse, error)) *MockClientWithResponsesInterface_PutApiQuotaPlansPlanIDWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PutApiQuotaSystemConfigWithBodyWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PutApiQuotaSystemConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PutApiQuotaSystemConfigResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutApiQuotaSystemConfigWithBodyWithResponse")
	}

	var r0 *admin.PutApiQuotaSystemConfigResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) (*admin.PutApiQuotaSystemConfigResponse, error)); ok {
		return returnFunc(ctx, contentType, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) *admin.PutApiQuotaSystemConfigResponse); ok {
		r0 = returnFunc(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PutApiQuotaSystemConfigResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithBodyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutApiQuotaSystemConfigWithBodyWithResponse'
type MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithBodyWithResponse_Call struct {
	*mock.Call
}

// PutApiQuotaSystemConfigWithBodyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - body io.Reader
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PutApiQuotaSystemConfigWithBodyWithResponse(ctx interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithBodyWithResponse_Call {
	return &MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithBodyWithResponse_Call{Call: _e.mock.On("PutApiQuotaSystemConfigWithBodyWithResponse",
		append([]interface{}{ctx, contentType, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithBodyWithResponse_Call) Run(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithBodyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithBodyWithResponse_Call) Return(putApiQuotaSystemConfigResponse *admin.PutApiQuotaSystemConfigResponse, err error) *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithBodyWithResponse_Call {
	_c.Call.Return(putApiQuotaSystemConfigResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithBodyWithResponse_Call) RunAndReturn(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...admin.RequestEditorFn) (*admin.PutApiQuotaSystemConfigResponse, error)) *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithBodyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// PutApiQuotaSystemConfigWithResponse provides a mock function for the type MockClientWithResponsesInterface
func (_mock *MockClientWithResponsesInterface) PutApiQuotaSystemConfigWithResponse(ctx context.Context, body admin.PutApiQuotaSystemConfigJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PutApiQuotaSystemConfigResponse, error) {
	// admin.RequestEditorFn
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutApiQuotaSystemConfigWithResponse")
	}

	var r0 *admin.PutApiQuotaSystemConfigResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.PutApiQuotaSystemConfigJSONRequestBody, ...admin.RequestEditorFn) (*admin.PutApiQuotaSystemConfigResponse, error)); ok {
		return returnFunc(ctx, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.PutApiQuotaSystemConfigJSONRequestBody, ...admin.RequestEditorFn) *admin.PutApiQuotaSystemConfigResponse); ok {
		r0 = returnFunc(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.PutApiQuotaSystemConfigResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, admin.PutApiQuotaSystemConfigJSONRequestBody, ...admin.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutApiQuotaSystemConfigWithResponse'
type MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithResponse_Call struct {
	*mock.Call
}

// PutApiQuotaSystemConfigWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - body admin.PutApiQuotaSystemConfigJSONRequestBody
//   - reqEditors ...admin.RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) PutApiQuotaSystemConfigWithResponse(ctx interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithResponse_Call {
	return &MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithResponse_Call{Call: _e.mock.On("PutApiQuotaSystemConfigWithResponse",
		append([]interface{}{ctx, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithResponse_Call) Run(run func(ctx context.Context, body admin.PutApiQuotaSystemConfigJSONRequestBody, reqEditors ...admin.RequestEditorFn)) *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 admin.PutApiQuotaSystemConfigJSONRequestBody
		if args[1] != nil {
			arg1 = args[1].(admin.PutApiQuotaSystemConfigJSONRequestBody)
		}
		var arg2 []admin.RequestEditorFn
		variadicArgs := make([]admin.RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(admin.RequestEditorFn)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithResponse_Call) Return(putApiQuotaSystemConfigResponse *admin.PutApiQuotaSystemConfigResponse, err error) *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithResponse_Call {
	_c.Call.Return(putApiQuotaSystemConfigResponse, err)
	return _c
}

func (_c *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithResponse_Call) RunAndReturn(run func(ctx context.Context, body admin.PutApiQuotaSystemConfigJSONRequestBody, reqEditors ...admin.RequestEditorFn) (*admin.PutApiQuotaSystemConfigResponse, error)) *MockClientWithResponsesInterface_PutApiQuotaSystemConfigWithResponse_Call {
	_c.Call.Return(run)
	return _c
}
