name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.commit.outputs.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Install Knope
        uses: knope-dev/action@v2.1.0
        with:
          version: 0.21.7

      - name: Prepare Release
        run: knope prepare-release --verbose

      - name: Store commit
        id: commit
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  release:
    needs: prepare-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare-release.outputs.sha }}

      - name: Install Knope
        uses: knope-dev/action@v2.1.0
        with:
          version: 0.21.7

      - name: Create Release
        run: knope release --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
